#!/usr/bin/env python3
"""Generates driver/pinnames.h and driver/Speak2Mic.inf.

Speak2Mic has exactly one cable, a pair of endpoints:
  "Speak2Mic Speaker" - playback device (applications play INTO the cable)
  "Speak2Mic Microphone"     - recording device, shown as a microphone
The endpoint names are looked up by Windows under
HKLM\\SYSTEM\\CurrentControlSet\\Control\\MediaCategories\\{pin name GUID}.
"""
import os
import datetime

MIN_OS = '10.0...19041'       # TargetOSVersion decoration of the INF models sections
MAX_CABLES = 1
# (Input GUID, Output GUID) per cable. Never change existing values: Windows caches them.
# Only the first pair is used (one cable); the rest are kept reserved.
GUIDS = [
    ("6001C8A7-E8F5-4058-A9E5-FCD4883FF68F", "28846C9C-5B44-464E-8559-DB6248541963"),
    ("856ABDAE-836A-43A2-8E19-30F66C4A57E1", "953C9B0C-84B4-40EF-ADFC-92B35F5ACAEE"),
    ("08D829CF-10AF-4B10-BA92-1FEB80E7E4D6", "C2A14C03-EA00-4CAC-9F68-59F86CFE6077"),
    ("DB3F0FAF-C42F-4A59-9B9B-6D17163D85F6", "C579600F-EC3F-416B-9D8C-A9D050CE45E5"),
    ("FA31AD29-ECFC-4939-8937-5020FFDA1500", "6EF03C1A-85F6-40AD-9D1D-6AA3EA408D80"),
    ("33ACE5BF-FADB-47F8-A756-EA2C410A1ABC", "4D168ECB-E59E-45A4-961C-8E27E47C61A1"),
    ("20EB6C7C-6D5D-482B-A708-11B7B84617E4", "1CEC88FD-896A-48EA-8259-A07568075521"),
    ("068C8107-3BB4-4E74-9BCA-C182F548F28A", "DA173D10-BD70-4D39-B852-F9FF1F824871"),
]
assert len(GUIDS) >= MAX_CABLES

HERE = os.path.dirname(os.path.abspath(__file__))

# Default ("OEM") format of the endpoints, read by Windows when it creates them - otherwise it picks one
# itself. = preset "Standard": 48 kHz, 16 bit; the speaker stereo, the microphone mono (MicChannels = 1).
DEFAULT_RATE, DEFAULT_BITS, DEFAULT_CHANNELS, DEFAULT_MIC_CHANNELS = 48000, 16, 2, 1


def oem_format_blob(rate, bits, channels):
    """PKEY_AudioEngine_OEMFormat value: a VT_BLOB PROPVARIANT (type, size) + WAVEFORMATEXTENSIBLE."""
    import struct
    mask = {1: 0x4, 2: 0x3, 4: 0x33, 6: 0x3F, 8: 0x63F}[channels]
    align = channels * bits // 8
    pcm = bytes.fromhex('0100000000001000800000aa00389b71')      # KSDATAFORMAT_SUBTYPE_PCM
    wfx = struct.pack('<HHIIHHHHI', 0xFFFE, channels, rate, rate * align, align, bits, 22, bits, mask) + pcm
    blob = struct.pack('<II', 0x41, len(wfx)) + wfx               # VT_BLOB, byte count
    return ','.join(f'{b:02X}' for b in blob)

# Every build gets a new version: Windows identifies a driver package by its INF, and an INF with an
# unchanged DriverVer is treated as "already imported" - the old Speak2Mic.sys would keep running.
NOW = datetime.datetime.now()
VERSION = (1, 0, NOW.timetuple().tm_yday, NOW.hour * 60 + NOW.minute)   # 1.0.<day of year>.<minute of day>
VERSION_STR = '.'.join(map(str, VERSION))
DRIVER_DATE = NOW.strftime('%m/%d/%Y')


def gen_version():
    lines = ['// Generated by gen.py at build time - do not edit.', '#pragma once',
             f'#define S2M_VER_MAJOR {VERSION[0]}', f'#define S2M_VER_MINOR {VERSION[1]}',
             f'#define S2M_VER_BUILD {VERSION[2]}', f'#define S2M_VER_REV   {VERSION[3]}',
             f'#define S2M_VER_STR   "{VERSION_STR}"', '']
    open(os.path.join(HERE, 'driver', 'version.h'), 'w', newline='\r\n').write('\n'.join(lines))


def guid_c(g):
    p = g.split('-')
    b = p[3] + p[4]
    tail = ', '.join('0x' + b[i:i + 2] for i in range(0, 16, 2))
    return f'{{ 0x{p[0]}, 0x{p[1]}, 0x{p[2]}, {{ {tail} }} }}'


def gen_header():
    lines = ['// Generated by gen.py - do not edit.', '#pragma once', '',
             f'#define S2M_MAX_CABLES {MAX_CABLES}', '',
             '// Pin name GUIDs: [cable][0] = "Speak2Mic Speaker" (render), [cable][1] = "Speak2Mic Microphone" (capture)',
             'static const GUID g_S2mPinNames[S2M_MAX_CABLES][2] = {']
    for gi, go in GUIDS[:MAX_CABLES]:
        lines.append(f'    {{ {guid_c(gi)},\n      {guid_c(go)} }},')
    lines += ['};', '',
              '// Subdevice (KS filter) names = reference strings of the device interfaces in the INF.',
              '// PortCls keeps the pointer passed to PcRegisterSubdevice, so these must be static strings.',
              '// Order per cable: WaveRender, TopoRender, WaveCapture, TopoCapture (see S2M_SUBDEVICE).',
              'static const PCWSTR g_S2mSubdeviceNames[S2M_MAX_CABLES][4] = {']
    for n in range(MAX_CABLES):
        lines.append('    { ' + ', '.join(f'L"{k}{n}"' for k in ('WaveRender', 'TopoRender', 'WaveCapture', 'TopoCapture')) + ' },')
    lines += ['};', '']
    open(os.path.join(HERE, 'driver', 'pinnames.h'), 'w', newline='\r\n').write('\n'.join(lines))


def gen_inf():
    L = []
    a = L.append
    a('; Speak2Mic.inf - generated by gen.py, do not edit by hand.')
    a('; Virtual audio cable: "Speak2Mic Speaker" (playback) -> "Speak2Mic Microphone" (microphone).')
    a('')
    a('[Version]')
    a('Signature="$WINDOWS NT$"')
    a('Class=MEDIA')
    a('ClassGuid={4d36e96c-e325-11ce-bfc1-08002be10318}')
    a('Provider=%ProviderName%')
    a(f'DriverVer={DRIVER_DATE},{VERSION_STR}')
    a('CatalogFile=Speak2Mic.cat')
    a('PnpLockdown=1')
    a('')
    a('[SourceDisksNames]')
    a('1=%DiskName%,,,')
    a('')
    a('[SourceDisksFiles]')
    a('Speak2Mic.sys=1')
    a('')
    a('[DestinationDirs]')
    a('DefaultDestDir=13')
    a('')
    a('[Manufacturer]')
    # TargetOSVersion: Windows 10 2004 (build 19041) and later. The driver imports ExAllocatePool2 (2004+), and
    # InfVerif (error 1199) wants DIRID 13 restricted to 10.0.16299 or later.
    a(f'%MfgName%=Speak2Mic,NTamd64.{MIN_OS},NTarm64.{MIN_OS}')
    a('')
    for arch in ('NTamd64', 'NTarm64'):
        a(f'[Speak2Mic.{arch}.{MIN_OS}]')
        a('%DeviceDesc%=Speak2Mic_Device,ROOT\\Speak2Mic')
        a('')
    a('[Speak2Mic_Device.NT]')
    a('Include=ks.inf,wdmaudio.inf')
    a('Needs=KS.Registration,WDMAUDIO.Registration')
    a('CopyFiles=Speak2Mic.CopyFiles')
    a('AddReg=Speak2Mic.AddReg,Speak2Mic.PinNames.AddReg')
    a('AddProperty=Speak2Mic.AddProperty')
    a('')
    a('; Device icon = icon resource 100 inside Speak2Mic.sys.')
    a('; DEVPKEY_DrvPkg_Icon (pid 6) is used by Device Manager, DEVPKEY_DrvPkg_BrandingIcon (pid 7) by Devices and Printers.')
    a('; 0x2012 = DEVPROP_TYPE_STRING_LIST')
    a('[Speak2Mic.AddProperty]')
    a('{CF73BB51-3ABF-44A2-85E0-9A3DC7A12132},6,0x2012,,"%13%\\Speak2Mic.sys,-100"')
    a('{CF73BB51-3ABF-44A2-85E0-9A3DC7A12132},7,0x2012,,"%13%\\Speak2Mic.sys,-100"')
    a('')
    a('[Speak2Mic.CopyFiles]')
    a('Speak2Mic.sys')
    a('')
    a('[Speak2Mic.AddReg]')
    a('HKR,,AssociatedFilters,,"wdmaud,swmidi,redbook"')
    a('HKR,,Driver,,Speak2Mic.sys')
    a('HKR,Drivers,SubClasses,,"wave,mixer"')
    a('HKR,Drivers\\wave\\wdmaud.drv,Driver,,wdmaud.drv')
    a('HKR,Drivers\\mixer\\wdmaud.drv,Driver,,wdmaud.drv')
    a('HKR,Drivers\\wave\\wdmaud.drv,Description,,%DeviceDesc%')
    a('HKR,Drivers\\mixer\\wdmaud.drv,Description,,%DeviceDesc%')
    a('')
    a('[Speak2Mic.PinNames.AddReg]')
    for n, (gi, go) in enumerate(GUIDS[:MAX_CABLES], 1):
        a(f'HKLM,%MediaCategories%\\{{{gi}}},Name,,%Cable{n}In%')
        a(f'HKLM,%MediaCategories%\\{{{gi}}},Display,1,00,00,00,00')
        a(f'HKLM,%MediaCategories%\\{{{go}}},Name,,%Cable{n}Out%')
        a(f'HKLM,%MediaCategories%\\{{{go}}},Display,1,00,00,00,00')
    a('')
    a('[Speak2Mic_Device.NT.Interfaces]')
    for n in range(MAX_CABLES):
        for kind, cats in (('WaveRender', ('AUDIO', 'RENDER', 'REALTIME')),
                           ('TopoRender', ('AUDIO', 'TOPOLOGY')),
                           ('WaveCapture', ('AUDIO', 'CAPTURE', 'REALTIME')),
                           ('TopoCapture', ('AUDIO', 'TOPOLOGY'))):
            for c in cats:
                a(f'AddInterface=%KSCATEGORY_{c}%,%KSNAME_{kind}{n}%,Speak2Mic.I.{kind}{n}')
    a('')
    for n in range(MAX_CABLES):
        for kind in ('WaveRender', 'TopoRender', 'WaveCapture', 'TopoCapture'):
            a(f'[Speak2Mic.I.{kind}{n}]')
            a(f'AddReg=Speak2Mic.I.{kind}{n}.AddReg')
            a(f'[Speak2Mic.I.{kind}{n}.AddReg]')
            a('HKR,,CLSID,,%Proxy.CLSID%')
            a(f'HKR,,FriendlyName,,%Cable{n + 1}{"In" if "Render" in kind else "Out"}%')
            if kind.startswith('Topo'):
                # Endpoint icon in Sound settings: resource 101 (speaker) / 102 (mic) of Speak2Mic.sys.
                icon = 101 if kind == 'TopoRender' else 102
                a(f'HKR,EP\\0,%PKEY_DeviceClass_IconPath%,,"%13%\\Speak2Mic.sys,-{icon}"')
                # Default format Windows gives the endpoint when it creates it (0x00000001 = REG_BINARY).
                a(f'HKR,EP\\0,%PKEY_AudioEngine_OEMFormat%,0x00000001,'
                  f'{oem_format_blob(DEFAULT_RATE, DEFAULT_BITS, DEFAULT_CHANNELS if kind == "TopoRender" else DEFAULT_MIC_CHANNELS)}')
            a('')
    a('[Speak2Mic_Device.NT.Services]')
    a('AddService=Speak2Mic,0x00000002,Speak2Mic_Service')
    a('')
    a('[Speak2Mic_Service]')
    a('DisplayName=%SvcDesc%')
    a('ServiceType=1')
    a('StartType=3')
    a('ErrorControl=1')
    a('ServiceBinary=%13%\\Speak2Mic.sys')
    a('AddReg=Speak2Mic.Params.AddReg')
    a('')
    a('; Defaults; 0x00010003 = REG_DWORD, do not overwrite values changed by the user.')
    a('[Speak2Mic.Params.AddReg]')
    a('HKR,Parameters,SampleRate,0x00010003,48000')
    a('HKR,Parameters,Channels,0x00010003,2')
    a('HKR,Parameters,LatencyMs,0x00010003,30')
    a('HKR,Parameters,BitsPerSample,0x00010003,16')   # defaults = preset "Standard"
    a('HKR,Parameters,MicChannels,0x00010003,1')      # mono microphone; 0 = as many channels as the speaker
    a('')
    a('[Strings]')
    a('ProviderName="Speak2Mic"')
    a('MfgName="Speak2Mic"')
    a('DeviceDesc="Speak2Mic"')
    a('SvcDesc="Speak2Mic driver"')
    a('DiskName="Speak2Mic disk"')
    a('MediaCategories="SYSTEM\\CurrentControlSet\\Control\\MediaCategories"')
    a('Proxy.CLSID="{17CCA71B-ECD7-11D0-B908-00A0C9223196}"')
    a('PKEY_DeviceClass_IconPath="{259abffc-50a7-47ce-af08-68c9a7d73366},12"')
    a('PKEY_AudioEngine_OEMFormat="{E4870E26-3CC5-4CD2-BA46-CA0A9A70ED04},3"')
    a('KSCATEGORY_AUDIO="{6994AD04-93EF-11D0-A3CC-00A0C9223196}"')
    a('KSCATEGORY_RENDER="{65E8773E-8F56-11D0-A3B9-00A0C9223196}"')
    a('KSCATEGORY_CAPTURE="{65E8773D-8F56-11D0-A3B9-00A0C9223196}"')
    a('KSCATEGORY_REALTIME="{EB115FFC-10C8-4964-831D-6DCB02E6F23F}"')
    a('KSCATEGORY_TOPOLOGY="{DDA54A40-1E4C-11D1-A050-405705C10000}"')
    for n in range(MAX_CABLES):
        for kind in ('WaveRender', 'TopoRender', 'WaveCapture', 'TopoCapture'):
            a(f'KSNAME_{kind}{n}="{kind}{n}"')
    for n in range(1, MAX_CABLES + 1):
        a(f'Cable{n}In="Speak2Mic Speaker"')
        a(f'Cable{n}Out="Speak2Mic Microphone"')
    a('')
    open(os.path.join(HERE, 'driver', 'Speak2Mic.inf'), 'w', newline='\r\n').write('\n'.join(L))


if __name__ == '__main__':
    gen_header()
    gen_inf()
    gen_version()
    print(f'driver/pinnames.h, driver/version.h and driver/Speak2Mic.inf generated (version {VERSION_STR})')
