// KS GUIDs that the MinGW ks.h/ksmedia.h only declare (DEFINE_GUIDSTRUCT ignores INITGUID there).
// Values come from the headers' own STATIC_* macros. The WDK build does not need this file.
#include "../common.h"

#define S2M_GUID(n) EXTERN_C const GUID n = { STATIC_##n }
S2M_GUID(KSCATEGORY_AUDIO);
S2M_GUID(KSCATEGORY_RENDER);
S2M_GUID(KSCATEGORY_CAPTURE);
S2M_GUID(KSCATEGORY_REALTIME);
S2M_GUID(KSCATEGORY_TOPOLOGY);
S2M_GUID(KSDATAFORMAT_TYPE_AUDIO);
S2M_GUID(KSDATAFORMAT_SUBTYPE_PCM);
S2M_GUID(KSDATAFORMAT_SUBTYPE_ANALOG);
S2M_GUID(KSDATAFORMAT_SUBTYPE_IEEE_FLOAT);
S2M_GUID(KSDATAFORMAT_SPECIFIER_WAVEFORMATEX);
S2M_GUID(KSDATAFORMAT_SPECIFIER_NONE);
S2M_GUID(KSNODETYPE_MICROPHONE);
S2M_GUID(KSNODETYPE_LINE_CONNECTOR);
S2M_GUID(PINNAME_VIDEO_CAPTURE);
S2M_GUID(KSPROPSETID_Pin);
S2M_GUID(KSPROPSETID_Audio);
S2M_GUID(KSNODETYPE_VOLUME);
S2M_GUID(KSNODETYPE_MUTE);
