// Program log implementation (see applog.h).
#include "applog.h"
#include "../driver/version.h"     // S2M_VER_STR: the build, generated by gen.py
#include <shlobj.h>
#include <aclapi.h>
#include <stdio.h>
#include <stdarg.h>
#include <wchar.h>

// FOLDERID_ProgramData, declared locally so no extra import library is needed.
static const GUID kFolderProgramData = { 0x62ab5d82, 0xfdc1, 0x4dc3, { 0xa9, 0xdd, 0x07, 0x0d, 0x1d, 0x49, 0x5d, 0x97 } };

static CRITICAL_SECTION g_cs;
static bool             g_open;
static wchar_t          g_dir[MAX_PATH];
static wchar_t          g_path[MAX_PATH];

const wchar_t* AppLogPath() { return g_path; }
const wchar_t* AppLogDir() { return g_dir; }

static void WriteUtf8(const wchar_t* text)
{
    HANDLE f = CreateFileW(g_path, FILE_APPEND_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE, nullptr, OPEN_ALWAYS,
                           FILE_ATTRIBUTE_NORMAL, nullptr);
    if (f == INVALID_HANDLE_VALUE) return;
    LARGE_INTEGER size = {};
    GetFileSizeEx(f, &size);
    DWORD written;
    if (size.QuadPart == 0)
    {
        static const BYTE bom[3] = { 0xEF, 0xBB, 0xBF };     // so Notepad shows Cyrillic correctly
        WriteFile(f, bom, 3, &written, nullptr);
    }
    int n = WideCharToMultiByte(CP_UTF8, 0, text, -1, nullptr, 0, nullptr, nullptr);
    if (n > 1)
    {
        char* buf = (char*)HeapAlloc(GetProcessHeap(), 0, n);
        if (buf)
        {
            WideCharToMultiByte(CP_UTF8, 0, text, -1, buf, n, nullptr, nullptr);
            WriteFile(f, buf, (DWORD)(n - 1), &written, nullptr);
            HeapFree(GetProcessHeap(), 0, buf);
        }
    }
    CloseHandle(f);
}

static bool IsElevated()
{
    HANDLE token = nullptr;
    TOKEN_ELEVATION el = {};
    DWORD size = 0;
    bool elevated = false;
    if (OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &token))
    {
        if (GetTokenInformation(token, TokenElevation, &el, sizeof(el), &size)) elevated = el.TokenIsElevated != 0;
        CloseHandle(token);
    }
    return elevated;
}

// Files an elevated Speak2Mic program creates in %ProgramData% are read-only for other users by default, so a
// panel started normally could not add to panel.log / events.log written by the one the installer started.
// An elevated program grants the Users group modify rights on the log folder, inherited by all files in it
// (existing ones included).
static void LetUsersWriteLogs(const wchar_t* dir)
{
    PACL oldDacl = nullptr, newDacl = nullptr;
    PSECURITY_DESCRIPTOR sd = nullptr;
    if (GetNamedSecurityInfoW(dir, SE_FILE_OBJECT, DACL_SECURITY_INFORMATION, nullptr, nullptr, &oldDacl, nullptr, &sd) != ERROR_SUCCESS)
        return;
    BYTE sid[SECURITY_MAX_SID_SIZE];
    DWORD cb = sizeof(sid);
    if (CreateWellKnownSid(WinBuiltinUsersSid, nullptr, sid, &cb))
    {
        EXPLICIT_ACCESSW ea = {};
        ea.grfAccessPermissions = FILE_GENERIC_READ | FILE_GENERIC_WRITE | DELETE;
        ea.grfAccessMode = GRANT_ACCESS;
        ea.grfInheritance = SUB_CONTAINERS_AND_OBJECTS_INHERIT;
        ea.Trustee.TrusteeForm = TRUSTEE_IS_SID;
        ea.Trustee.TrusteeType = TRUSTEE_IS_WELL_KNOWN_GROUP;
        ea.Trustee.ptstrName = (LPWSTR)sid;
        if (SetEntriesInAclW(1, &ea, oldDacl, &newDacl) == ERROR_SUCCESS)
        {
            SetNamedSecurityInfoW((LPWSTR)dir, SE_FILE_OBJECT, DACL_SECURITY_INFORMATION, nullptr, nullptr, newDacl, nullptr);
            LocalFree(newDacl);
        }
    }
    LocalFree(sd);
}

void AppLogOpen(const wchar_t* name)
{
    InitializeCriticalSection(&g_cs);

    PWSTR programData = nullptr;
    if (SUCCEEDED(SHGetKnownFolderPath(kFolderProgramData, 0, nullptr, &programData)))
    {
        _snwprintf(g_dir, MAX_PATH, L"%ls\\Speak2Mic\\logs", programData);
        CoTaskMemFree(programData);
    }
    else
    {
        wcscpy(g_dir, L"C:\\ProgramData\\Speak2Mic\\logs");
    }
    g_dir[MAX_PATH - 1] = 0;
    SHCreateDirectoryExW(nullptr, g_dir, nullptr);
    if (IsElevated()) LetUsersWriteLogs(g_dir);

    _snwprintf(g_path, MAX_PATH, L"%ls\\%ls.log", g_dir, name);
    g_path[MAX_PATH - 1] = 0;

    WIN32_FILE_ATTRIBUTE_DATA fa;
    if (GetFileAttributesExW(g_path, GetFileExInfoStandard, &fa) && fa.nFileSizeLow > 1024 * 1024)
    {
        wchar_t old[MAX_PATH];
        _snwprintf(old, MAX_PATH, L"%ls\\%ls.old.log", g_dir, name);
        old[MAX_PATH - 1] = 0;
        MoveFileExW(g_path, old, MOVEFILE_REPLACE_EXISTING);
    }
    g_open = true;

    wchar_t exe[MAX_PATH];
    GetModuleFileNameW(nullptr, exe, MAX_PATH);
    OSVERSIONINFOEXW os = { sizeof(os) };
    typedef LONG(WINAPI * RtlGetVersionFn)(OSVERSIONINFOEXW*);
    RtlGetVersionFn getVersion = (RtlGetVersionFn)GetProcAddress(GetModuleHandleW(L"ntdll.dll"), "RtlGetVersion");
    if (getVersion) getVersion(&os);
    AppLog(L"==== %ls started (pid %lu), Speak2Mic build %ls, Windows %lu.%lu.%lu ====", exe, GetCurrentProcessId(),
           L"" S2M_VER_STR, os.dwMajorVersion, os.dwMinorVersion, os.dwBuildNumber);
}

void AppLog(const wchar_t* fmt, ...)
{
    if (!g_open) return;
    SYSTEMTIME t;
    GetLocalTime(&t);
    wchar_t line[2048];
    int n = _snwprintf(line, 2048, L"%04u-%02u-%02u %02u:%02u:%02u.%03u  ", t.wYear, t.wMonth, t.wDay,
                       t.wHour, t.wMinute, t.wSecond, t.wMilliseconds);
    va_list args;
    va_start(args, fmt);
    int m = _vsnwprintf(line + n, 2048 - n - 3, fmt, args);
    va_end(args);
    if (m < 0) m = 2048 - n - 3;
    wcscpy(line + n + m, L"\r\n");

    EnterCriticalSection(&g_cs);
    WriteUtf8(line);
    LeaveCriticalSection(&g_cs);
}

void AppLogText(const wchar_t* prefix, const wchar_t* text)
{
    const wchar_t* p = text;
    while (*p)
    {
        const wchar_t* e = p;
        while (*e && *e != L'\n' && *e != L'\r') e++;
        if (e > p)
        {
            AppLog(L"%ls%.*ls", prefix, (int)(e - p), p);
        }
        while (*e == L'\r' || *e == L'\n') e++;
        p = e;
    }
}
