// s2mpanel - control panel for Speak2Mic.
//
//  * Signal quality: sample rate, bit depth, channels and latency of the driver
//    (presets or manual). "Apply" writes the driver settings and restarts the device; it asks for
//    administrator rights only at that moment (re-launches itself elevated with --apply).
//  * Signal indication: live per-channel peak meters of "Speak2Mic Speaker" and "Speak2Mic Microphone".
#include "audio.h"
#include "lang.h"
#include "applog.h"
#include "audiosvc.h"
#include "devctl.h"
#include "ready.h"
#include "mp3player.h"
#include "autostart.h"
#include "../driver/version.h"   // S2M_VER_STR, generated by gen.py for every build
#include <commctrl.h>
#include <commdlg.h>
#include <shellapi.h>
#include <setupapi.h>
#include <stdio.h>
#include <wchar.h>
#include <math.h>


enum
{
    IDC_PRESET = 100, IDC_RATE, IDC_BITS, IDC_CHANNELS, IDC_LATENCY, IDC_LATENCY_UD, IDC_APPLY,
    IDC_SETTINGS_STATUS,
    IDC_IN_LABEL, IDC_IN_DB, IDC_IN_METER, IDC_IN_FORMAT,
    IDC_OUT_LABEL, IDC_OUT_DB, IDC_OUT_METER, IDC_OUT_FORMAT,
    IDC_GROUP1, IDC_GROUP2,
    IDC_L_PRESET, IDC_L_RATE, IDC_L_BITS, IDC_L_CHANNELS, IDC_L_LATENCY, IDC_L_LANG, IDC_LANG,
    IDC_L_MICCHANNELS, IDC_MICCHANNELS, IDC_TEST,
    IDC_GROUP3, IDC_L_SPKNAME, IDC_SPKNAME, IDC_L_MICNAME, IDC_MICNAME, IDC_RENAME, IDC_RENAME_STATUS,
    IDC_RESET_ALL, IDC_MIXER, IDC_CLEARLOG, IDC_L_MICVOL, IDC_MICVOL, IDC_MICVOL_VALUE, IDC_MICMUTE,
    IDC_EXPORT, IDC_IMPORT, IDC_IO_STATUS, IDC_PLAY, IDC_AUTOSTART,
};

// Default endpoint names (driver pin names, see gen.py); the user can rename them in the panel.
static const wchar_t kDefaultName[2][32] = { L"Speak2Mic Speaker", L"Speak2Mic Microphone" };
static const int kMicMaxPercent = 300;    // microphone slider: 100 % = 0 dB, 300 % = +9.5 dB
#define S2M_USER_KEY L"Software\\Speak2Mic"

enum { TIMER_METERS = 1, TIMER_REFRESH = 2, TIMER_FORMAT = 3, TIMER_MP3 = 4 };

// ---------------------------------------------------------------------------
// Settings

struct Settings
{
    DWORD rate, channels, bits, latency;
    DWORD micChannels;  // "Speak2Mic Microphone": 0 = as many as the speaker (driver setting MicChannels)
};

struct Preset
{
    const wchar_t* name;
    DWORD rate, bits, channels;
};

static const Preset kPresets[] = {
    { TR(L"Своя настройка"), 0, 0, 0 },
    { TR(L"Голос — 16 кГц · 16 бит · моно"), 16000, 16, 1 },
    { TR(L"Стандарт — 48 кГц · 16 бит · стерео"), 48000, 16, 2 },
    { TR(L"Высокое — 48 кГц · 24 бит · стерео"), 48000, 24, 2 },
    { TR(L"Студия — 96 кГц · 24 бит · стерео"), 96000, 24, 2 },
    { TR(L"Максимум — 192 кГц · 32 бит · стерео"), 192000, 32, 2 },
};
static const DWORD kRates[] = { 8000, 11025, 16000, 22050, 32000, 44100, 48000, 88200, 96000, 176400, 192000 };
static const DWORD kBits[] = { 0, 16, 24, 32 };
static const wchar_t* kBitsNames[] = { TR(L"Авто (16–32)"), TR(L"16 бит"), TR(L"24 бит"), TR(L"32 бит") };
static const DWORD kChannels[] = { 1, 2, 4, 6, 8 };
static const wchar_t* kChannelNames[] = { TR(L"1 (моно)"), TR(L"2 (стерео)"), TR(L"4 (квадро)"), L"6 (5.1)", L"8 (7.1)" };

static bool ReadSettings(Settings* s)
{
    s->rate = 48000; s->channels = 2; s->bits = 16; s->latency = 30;   // preset "Standard"
    s->micChannels = 1;     // mono microphone by default (all presets)
    HKEY key;
    if (RegOpenKeyExW(HKEY_LOCAL_MACHINE, S2M_PARAMS_KEY, 0, KEY_READ, &key) != ERROR_SUCCESS)
    {
        return false;
    }
    struct { const wchar_t* name; DWORD* value; } items[] = {
        { L"SampleRate", &s->rate }, { L"Channels", &s->channels }, { L"MicChannels", &s->micChannels },
        { L"BitsPerSample", &s->bits }, { L"LatencyMs", &s->latency } };
    for (auto& it : items)
    {
        DWORD v = 0, size = sizeof(v), type = 0;
        if (RegQueryValueExW(key, it.name, nullptr, &type, (BYTE*)&v, &size) == ERROR_SUCCESS && type == REG_DWORD)
        {
            *it.value = v;
        }
    }
    RegCloseKey(key);
    return true;
}

// Exit codes of "s2mpanel --apply": 0 ok, 2 driver not installed, 3 device not found, 4 restart failed,
// 5 a reboot is needed to finish.
static int ApplySettings(const Settings& s)
{
    HKEY key;
    if (RegOpenKeyExW(HKEY_LOCAL_MACHINE, S2M_PARAMS_KEY, 0, KEY_SET_VALUE, &key) != ERROR_SUCCESS)
    {
        AppLog(L"apply: driver settings key not found (driver not installed)");
        return 2;
    }
    struct { const wchar_t* name; DWORD value; } items[] = {
        { L"SampleRate", s.rate }, { L"Channels", s.channels }, { L"MicChannels", s.micChannels },
        { L"BitsPerSample", s.bits }, { L"LatencyMs", s.latency } };
    for (auto& it : items)
    {
        RegSetValueExW(key, it.name, 0, REG_DWORD, (const BYTE*)&it.value, sizeof(DWORD));
    }
    RegDeleteValueW(key, L"CableCount");   // left over from versions with several cables
    RegCloseKey(key);

    bool found = false, reboot = false;
    // audiodg.exe keeps Speak2Mic streams open (e.g. default device): stop Windows Audio meanwhile.
    AudioServices stopped;
    AudioStopServices(false, &stopped);
    bool ok = S2mRestartDevice(&found, &reboot);
    AudioStartServices(&stopped);
    if (found && ok && !reboot)
    {
        // leftover endpoint records (the first restart after an installation leaves the installation's pair)
        bool com = SUCCEEDED(CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED));
        S2mCleanupOrphanEndpoints(8000);
        if (com) CoUninitialize();
    }
    int rc = !found ? 3 : (!ok ? 4 : (reboot ? 5 : 0));
    AppLog(L"apply: rate=%lu channels=%lu bits=%lu latency=%lu -> device %ls, result %d",
           s.rate, s.channels, s.bits, s.latency, found ? L"found" : L"NOT found", rc);
    AppLog(L"apply: microphone channels %lu (0 = as the speaker)", s.micChannels);
    return rc;
}

static bool IsElevated()
{
    HANDLE token = nullptr;
    TOKEN_ELEVATION el = {};
    DWORD size = 0;
    bool elevated = false;
    if (OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &token))
    {
        if (GetTokenInformation(token, TokenElevation, &el, sizeof(el), &size))
        {
            elevated = el.TokenIsElevated != 0;
        }
        CloseHandle(token);
    }
    return elevated;
}

// Runs "s2mpanel --apply ..." elevated and returns its exit code (-1 if UAC was declined).
static int ApplyElevated(HWND hwnd, const Settings& s)
{
    wchar_t exe[MAX_PATH], args[128];
    GetModuleFileNameW(nullptr, exe, MAX_PATH);
    _snwprintf(args, 128, L"--apply %lu %lu %lu %lu %lu", s.rate, s.channels, s.bits, s.latency, s.micChannels);
    args[127] = 0;

    SHELLEXECUTEINFOW sei = {};
    sei.cbSize = sizeof(sei);
    sei.fMask = SEE_MASK_NOCLOSEPROCESS;
    sei.hwnd = hwnd;
    sei.lpVerb = L"runas";
    sei.lpFile = exe;
    sei.lpParameters = args;
    sei.nShow = SW_HIDE;
    if (!ShellExecuteExW(&sei) || !sei.hProcess)
    {
        return -1;
    }
    WaitForSingleObject(sei.hProcess, 60000);
    DWORD code = 4;
    GetExitCodeProcess(sei.hProcess, &code);
    CloseHandle(sei.hProcess);
    return (int)code;
}

// ---------------------------------------------------------------------------
// Peak meter control ("S2mMeter")

struct MeterState
{
    int   channels;
    float level[S2M_MAX_METER_CHANNELS];     // displayed level, 0..1
    float hold[S2M_MAX_METER_CHANNELS];      // peak hold, 0..1
    DWORD holdUntil[S2M_MAX_METER_CHANNELS];
};

static float DbFrac(float v)                 // -60..0 dBFS -> 0..1
{
    if (v <= 0.001f) return 0;
    float db = 20.0f * log10f(v);
    float f = (db + 60.0f) / 60.0f;
    return f < 0 ? 0 : (f > 1 ? 1 : f);
}

static void FillBox(HDC dc, int l, int t, int r, int b, COLORREF c)
{
    if (r <= l || b <= t) return;
    RECT rc = { l, t, r, b };
    HBRUSH br = CreateSolidBrush(c);
    FillRect(dc, &rc, br);
    DeleteObject(br);
}

static LRESULT CALLBACK MeterProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    MeterState* st = (MeterState*)GetWindowLongPtrW(hwnd, GWLP_USERDATA);
    switch (msg)
    {
    case WM_NCCREATE:
        st = (MeterState*)calloc(1, sizeof(MeterState));
        SetWindowLongPtrW(hwnd, GWLP_USERDATA, (LONG_PTR)st);
        break;
    case WM_NCDESTROY:
        free(st);
        SetWindowLongPtrW(hwnd, GWLP_USERDATA, 0);
        break;
    case WM_ERASEBKGND:
        return 1;
    case WM_PAINT:
    {
        PAINTSTRUCT ps;
        HDC hdc = BeginPaint(hwnd, &ps);
        RECT rc;
        GetClientRect(hwnd, &rc);
        int w = rc.right, h = rc.bottom;

        // Double-buffered drawing.
        HDC dc = CreateCompatibleDC(hdc);
        HBITMAP bmp = CreateCompatibleBitmap(hdc, w, h);
        HGDIOBJ old = SelectObject(dc, bmp);
        FillBox(dc, 0, 0, w, h, RGB(28, 28, 32));

        int n = st && st->channels > 0 ? st->channels : 2;
        int gap = 2;
        int bh = (h - 4 - gap * (n - 1)) / n;
        int x0 = 2, x1 = w - 2, span = x1 - x0;
        // Zones: green up to -12 dB, yellow up to -3 dB, red above.
        int zy = x0 + (int)(span * 0.80f), zr = x0 + (int)(span * 0.95f);

        for (int c = 0; c < n; c++)
        {
            int top = 2 + c * (bh + gap), bot = top + bh;
            float lv = st ? DbFrac(st->level[c]) : 0;
            float hd = st ? DbFrac(st->hold[c]) : 0;
            int xl = x0 + (int)(span * lv);

            FillBox(dc, x0, top, zy, bot, RGB(22, 60, 30));             // unlit zones
            FillBox(dc, zy, top, zr, bot, RGB(64, 60, 20));
            FillBox(dc, zr, top, x1, bot, RGB(70, 24, 24));
            FillBox(dc, x0, top, xl < zy ? xl : zy, bot, RGB(40, 200, 80));
            if (xl > zy) FillBox(dc, zy, top, xl < zr ? xl : zr, bot, RGB(230, 200, 40));
            if (xl > zr) FillBox(dc, zr, top, xl, bot, RGB(235, 60, 50));
            if (hd > 0)
            {
                int xh = x0 + (int)(span * hd);
                FillBox(dc, xh - 2, top, xh, bot, RGB(240, 240, 240));
            }
        }
        // Scale ticks every 6 dB.
        for (int db = -54; db < 0; db += 6)
        {
            int x = x0 + span * (db + 60) / 60;
            FillBox(dc, x, 0, x + 1, h, RGB(0, 0, 0));
        }

        BitBlt(hdc, 0, 0, w, h, dc, 0, 0, SRCCOPY);
        SelectObject(dc, old);
        DeleteObject(bmp);
        DeleteDC(dc);
        EndPaint(hwnd, &ps);
        return 0;
    }
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

// Feeds fresh peaks into a meter: fast attack, ~20 dB/s release, 1.5 s peak hold.
static float UpdateMeter(HWND meter, const float* peaks, int n)
{
    MeterState* st = (MeterState*)GetWindowLongPtrW(meter, GWLP_USERDATA);
    if (!st) return 0;
    DWORD now = GetTickCount();
    float maxLevel = 0;
    st->channels = n;
    for (int c = 0; c < n; c++)
    {
        float lv = st->level[c] * 0.927f;
        if (peaks[c] > lv) lv = peaks[c];
        st->level[c] = lv;
        if (lv >= st->hold[c] || now > st->holdUntil[c])
        {
            st->hold[c] = lv;
            st->holdUntil[c] = now + 1500;
        }
        if (lv > maxLevel) maxLevel = lv;
    }
    InvalidateRect(meter, nullptr, FALSE);
    return maxLevel;
}

static void ClearMeter(HWND meter)
{
    MeterState* st = (MeterState*)GetWindowLongPtrW(meter, GWLP_USERDATA);
    if (st)
    {
        ZeroMemory(st, sizeof(*st));
    }
    InvalidateRect(meter, nullptr, FALSE);
}

// ---------------------------------------------------------------------------
// Main window state

static HINSTANCE   g_inst;
static HWND        g_wnd;
static HFONT       g_font, g_fontBold;
static HICON       g_toolIcons[5];      // reset / export / import / mixer / clear log (resources 10..14), for the DPI
static UINT        g_dpi = 96;
static bool        g_elevated;
static bool        g_driverInstalled;
static Settings    g_settings;
static bool        g_updatingControls;
static Settings    g_formatTarget;      // default format to put on the endpoints after "Apply"
static int         g_formatTries;       // remaining attempts (endpoints re-appear a few seconds after restart)
static bool        g_formatOnlyIfWrong; // startup check: touch only endpoints whose format the driver no longer supports
static wchar_t     g_driverLogMark[32]; // driver log lines after this time stamp are copied into panel.log
static void DumpDriverLog(const wchar_t* reason);

static AudioDevice g_devs[128];
static int         g_devCount;

static LevelMeter  g_meterIn, g_meterOut;
static bool        g_inFound, g_outFound;

static HWND Ctl(int id) { return GetDlgItem(g_wnd, id); }
static int S(int v) { return MulDiv(v, (int)g_dpi, 96); }

static void SetText(int id, const wchar_t* text)
{
    wchar_t cur[512];
    GetWindowTextW(Ctl(id), cur, 512);
    if (wcscmp(cur, text) != 0) SetWindowTextW(Ctl(id), text);
}

// Status line = a drop-down list of events with date and time, kept across sessions in
// %ProgramData%\Speak2Mic\logs\events.log (UTF-16, one event per line; the last kMaxEvents are kept).
// The newest is at the bottom and shown while the list is closed.
static const int kMaxEvents = 500;

static void EventsPath(wchar_t* path)
{
    _snwprintf(path, MAX_PATH, L"%ls\\events.log", AppLogDir());
    path[MAX_PATH - 1] = 0;
}

static void AppendEventFile(const wchar_t* line)
{
    wchar_t path[MAX_PATH];
    EventsPath(path);
    HANDLE f = CreateFileW(path, FILE_APPEND_DATA | FILE_READ_ATTRIBUTES, FILE_SHARE_READ | FILE_SHARE_WRITE, nullptr,
                           OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (f == INVALID_HANDLE_VALUE)
    {
        AppLog(L"event log: cannot write %ls (%lu)", path, GetLastError());
        return;
    }
    DWORD written = 0;
    LARGE_INTEGER size = {};
    GetFileSizeEx(f, &size);
    if (size.QuadPart == 0)
    {
        const WORD bom = 0xFEFF;
        WriteFile(f, &bom, sizeof(bom), &written, nullptr);
    }
    WriteFile(f, line, (DWORD)(wcslen(line) * sizeof(wchar_t)), &written, nullptr);
    WriteFile(f, L"\r\n", 2 * sizeof(wchar_t), &written, nullptr);
    CloseHandle(f);
}

// Reads the saved events into the list (the last kMaxEvents) and trims the file when it grew beyond that.
static void LoadEvents()
{
    wchar_t path[MAX_PATH];
    EventsPath(path);
    HANDLE f = CreateFileW(path, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, nullptr, OPEN_EXISTING, 0, nullptr);
    if (f == INVALID_HANDLE_VALUE) return;
    DWORD size = GetFileSize(f, nullptr), got = 0;
    wchar_t* text = size >= 2 && size < 8 * 1024 * 1024 ? (wchar_t*)HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, size + 4) : nullptr;
    bool ok = text && ReadFile(f, text, size, &got, nullptr) && got == size;
    CloseHandle(f);
    if (!ok)
    {
        if (text) HeapFree(GetProcessHeap(), 0, text);
        return;
    }
    wchar_t* p = text[0] == 0xFEFF ? text + 1 : text;
    // Line starts, keep the last kMaxEvents.
    static wchar_t* lines[20000];
    int n = 0;
    for (wchar_t* q = p; *q && n < 20000;)
    {
        wchar_t* e = q;
        while (*e && *e != L'\r' && *e != L'\n') e++;
        bool end = !*e;
        *e = 0;
        if (*q) lines[n++] = q;
        if (end) break;
        q = e + 1;
        while (*q == L'\r' || *q == L'\n') q++;
    }
    int from = n > kMaxEvents ? n - kMaxEvents : 0;
    HWND box = Ctl(IDC_IO_STATUS);
    for (int i = from; i < n; i++) SendMessageW(box, CB_ADDSTRING, 0, (LPARAM)lines[i]);
    int count = (int)SendMessageW(box, CB_GETCOUNT, 0, 0);
    if (count > 0) SendMessageW(box, CB_SETCURSEL, count - 1, 0);
    if (from > 0)
    {
        // Trim: rewrite the file with the kept events.
        HANDLE w = CreateFileW(path, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
        if (w != INVALID_HANDLE_VALUE)
        {
            DWORD written = 0;
            const WORD bom = 0xFEFF;
            WriteFile(w, &bom, sizeof(bom), &written, nullptr);
            for (int i = from; i < n; i++)
            {
                WriteFile(w, lines[i], (DWORD)(wcslen(lines[i]) * sizeof(wchar_t)), &written, nullptr);
                WriteFile(w, L"\r\n", 2 * sizeof(wchar_t), &written, nullptr);
            }
            CloseHandle(w);
        }
    }
    HeapFree(GetProcessHeap(), 0, text);
}

// Width of a text in the event list's font (pixels).
static int EventTextWidth(const wchar_t* text)
{
    HWND box = Ctl(IDC_IO_STATUS);
    HDC dc = GetDC(box);
    HGDIOBJ old = SelectObject(dc, (HFONT)SendMessageW(box, WM_GETFONT, 0, 0));
    SIZE sz = {};
    GetTextExtentPoint32W(dc, text, (int)wcslen(text), &sz);
    SelectObject(dc, old);
    ReleaseDC(box, dc);
    return sz.cx;
}

// The open list is as wide as its longest line (up to the screen's edge), so every event can be read in full.
static int g_eventsWidest;
static void FitEventList(const wchar_t* added)
{
    HWND box = Ctl(IDC_IO_STATUS);
    if (!added)
    {
        g_eventsWidest = 0;
        int count = (int)SendMessageW(box, CB_GETCOUNT, 0, 0);
        wchar_t t[700];
        for (int i = 0; i < count; i++)
            if (SendMessageW(box, CB_GETLBTEXTLEN, i, 0) < 699 && SendMessageW(box, CB_GETLBTEXT, i, (LPARAM)t) >= 0)
            {
                int w = EventTextWidth(t);
                if (w > g_eventsWidest) g_eventsWidest = w;
            }
    }
    else
    {
        int w = EventTextWidth(added);
        if (w > g_eventsWidest) g_eventsWidest = w;
    }
    RECT r, work;
    GetWindowRect(box, &r);
    SystemParametersInfoW(SPI_GETWORKAREA, 0, &work, 0);
    int want = g_eventsWidest + GetSystemMetrics(SM_CXVSCROLL) + 12;
    int maxWidth = work.right - r.left;
    if (want > maxWidth) want = maxWidth;
    if (want < r.right - r.left) want = r.right - r.left;
    SendMessageW(box, CB_SETDROPPEDWIDTH, want, 0);
}

// Tooltip of the closed event list: the full text of the shown event when it does not fit.
static HWND    g_eventTip;
static wchar_t g_eventTipText[700];
static void EventTipText(NMTTDISPINFOW* info)
{
    HWND box = Ctl(IDC_IO_STATUS);
    g_eventTipText[0] = 0;
    int sel = (int)SendMessageW(box, CB_GETCURSEL, 0, 0);
    if (sel >= 0 && SendMessageW(box, CB_GETLBTEXTLEN, sel, 0) < 699)
    {
        SendMessageW(box, CB_GETLBTEXT, sel, (LPARAM)g_eventTipText);
        RECT r;
        GetClientRect(box, &r);
        int room = r.right - r.left - GetSystemMetrics(SM_CXVSCROLL) - 8;   // minus the arrow button
        if (EventTextWidth(g_eventTipText) <= room) g_eventTipText[0] = 0;   // fits: no tip
    }
    info->lpszText = g_eventTipText;
}

static void AddEvent(const wchar_t* text)
{
    if (!text || !*text) return;
    SYSTEMTIME st;
    GetLocalTime(&st);
    wchar_t date[40] = L"", time[40] = L"", item[640];
    GetDateFormatEx(LOCALE_NAME_USER_DEFAULT, DATE_SHORTDATE, &st, nullptr, date, 40, nullptr);
    GetTimeFormatEx(LOCALE_NAME_USER_DEFAULT, 0, &st, nullptr, time, 40);
    _snwprintf(item, 640, L"%ls %ls  %ls", date, time, text);
    item[639] = 0;
    for (wchar_t* c = item; *c; c++)
        if (*c == L'\r' || *c == L'\n') *c = L' ';      // one line per event in the file
    HWND box = Ctl(IDC_IO_STATUS);
    int index = (int)SendMessageW(box, CB_ADDSTRING, 0, (LPARAM)item);     // newest at the bottom (no CBS_SORT)
    FitEventList(item);
    SendMessageW(box, CB_SETCURSEL, index, 0);          // shown when closed; the open list scrolls to it
    while (SendMessageW(box, CB_GETCOUNT, 0, 0) > kMaxEvents) SendMessageW(box, CB_DELETESTRING, 0, 0);
    AppendEventFile(item);
    AppLog(L"event: %ls", text);
}

static void ClearEvents()
{
    SendMessageW(Ctl(IDC_IO_STATUS), CB_RESETCONTENT, 0, 0);
    g_eventsWidest = 0;
    wchar_t path[MAX_PATH];
    EventsPath(path);
    DeleteFileW(path);
    AppLog(L"event log cleared");
    AddEvent(TR(L"Журнал событий очищен."));     // the new log starts with the fact that it was cleared
}

static HWND Create(const wchar_t* cls, const wchar_t* text, DWORD style, int id, DWORD exStyle = 0)
{
    HWND h = CreateWindowExW(exStyle, cls, text, WS_CHILD | WS_VISIBLE | style, 0, 0, 10, 10, g_wnd,
                             (HMENU)(INT_PTR)id, g_inst, nullptr);
    SendMessageW(h, WM_SETFONT, (WPARAM)g_font, FALSE);
    return h;
}

static void ComboAdd(int id, const wchar_t* text, LPARAM data)
{
    int i = (int)SendMessageW(Ctl(id), CB_ADDSTRING, 0, (LPARAM)text);
    SendMessageW(Ctl(id), CB_SETITEMDATA, i, data);
}
static int ComboSel(int id) { return (int)SendMessageW(Ctl(id), CB_GETCURSEL, 0, 0); }
static LPARAM ComboData(int id) { int i = ComboSel(id); return i < 0 ? -1 : SendMessageW(Ctl(id), CB_GETITEMDATA, i, 0); }
static void ComboSelectData(int id, LPARAM data)
{
    int n = (int)SendMessageW(Ctl(id), CB_GETCOUNT, 0, 0);
    for (int i = 0; i < n; i++)
    {
        if (SendMessageW(Ctl(id), CB_GETITEMDATA, i, 0) == data)
        {
            SendMessageW(Ctl(id), CB_SETCURSEL, i, 0);
            return;
        }
    }
}

// ---------------------------------------------------------------------------
// Layout (all coordinates in 96-DPI units, scaled by S()).

static void Place(int id, int x, int y, int w, int h)
{
    SetWindowPos(Ctl(id), nullptr, S(x), S(y), S(w), S(h), SWP_NOZORDER | SWP_NOACTIVATE);
}

// Icon buttons in the top left corner: (re)loads their icons at the current DPI.
static void ApplyToolIcons()
{
    const int ids[5] = { IDC_RESET_ALL, IDC_EXPORT, IDC_IMPORT, IDC_MIXER, IDC_CLEARLOG };
    int size = MulDiv(20, (int)g_dpi, 96);
    for (int i = 0; i < 5; i++)
    {
        HICON old = g_toolIcons[i];
        g_toolIcons[i] = (HICON)LoadImageW(g_inst, MAKEINTRESOURCEW(10 + i), IMAGE_ICON, size, size, 0);
        SendMessageW(GetDlgItem(g_wnd, ids[i]), BM_SETIMAGE, IMAGE_ICON, (LPARAM)g_toolIcons[i]);
        if (old) DestroyIcon(old);
    }
}

static void ApplyFonts()
{
    if (g_font) DeleteObject(g_font);
    if (g_fontBold) DeleteObject(g_fontBold);
    g_font = CreateFontW(-MulDiv(9, (int)g_dpi, 72), 0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET, 0, 0,
                         CLEARTYPE_QUALITY, 0, L"Segoe UI");
    g_fontBold = CreateFontW(-MulDiv(9, (int)g_dpi, 72), 0, 0, 0, FW_SEMIBOLD, 0, 0, 0, DEFAULT_CHARSET, 0, 0,
                             CLEARTYPE_QUALITY, 0, L"Segoe UI");
    for (HWND c = GetWindow(g_wnd, GW_CHILD); c; c = GetWindow(c, GW_HWNDNEXT))
    {
        SendMessageW(c, WM_SETFONT, (WPARAM)g_font, TRUE);
    }
    SendMessageW(Ctl(IDC_IN_DB), WM_SETFONT, (WPARAM)g_fontBold, TRUE);
    SendMessageW(Ctl(IDC_OUT_DB), WM_SETFONT, (WPARAM)g_fontBold, TRUE);
}

static void Layout()
{
    const int L1 = 24, C1 = 120, W1 = 160, L2 = 304, C2 = 408, W2 = 164;

    // Top row: reset everything (left), language (right).
    Place(IDC_RESET_ALL, 12, 7, 32, 28);    Place(IDC_EXPORT, 48, 7, 32, 28);    Place(IDC_IMPORT, 84, 7, 32, 28);
    Place(IDC_MIXER, 128, 7, 32, 28);
    Place(IDC_L_LANG, 300, 12, 120, 20);    Place(IDC_LANG, 428, 8, 160, 400);

    Place(IDC_GROUP1, 12, 42, 576, 196);
    Place(IDC_L_PRESET, L1, 70, 90, 20);    Place(IDC_PRESET, C1, 66, 452, 300);
    Place(IDC_L_RATE, L1, 104, 90, 20);     Place(IDC_RATE, C1, 100, W1, 300);
    Place(IDC_L_BITS, L2, 104, 100, 20);    Place(IDC_BITS, C2, 100, W2, 300);
    Place(IDC_L_CHANNELS, L1, 138, 90, 20); Place(IDC_CHANNELS, C1, 134, W1, 300);
    Place(IDC_L_LATENCY, L2, 138, 100, 20); Place(IDC_LATENCY, C2, 134, 70, 23);
    Place(IDC_L_MICCHANNELS, L1, 172, 150, 20); Place(IDC_MICCHANNELS, 180, 168, 170, 300);
    Place(IDC_APPLY, C2, 167, W2, 27);
    Place(IDC_SETTINGS_STATUS, L1, 204, 548, 28);
    SendMessageW(Ctl(IDC_LATENCY_UD), UDM_SETBUDDY, (WPARAM)Ctl(IDC_LATENCY), 0);

    Place(IDC_GROUP2, 12, 246, 576, 252);
    Place(IDC_IN_LABEL, L1, 272, 400, 20);  Place(IDC_IN_DB, 430, 272, 142, 20);
    Place(IDC_IN_METER, L1, 294, 548, 34);
    Place(IDC_IN_FORMAT, L1, 332, 330, 20); Place(IDC_TEST, 362, 330, 102, 26);   // test: under the speaker meter
    Place(IDC_PLAY, 470, 330, 102, 26);                                           // music: right of "Test"
    Place(IDC_OUT_LABEL, L1, 362, 400, 20); Place(IDC_OUT_DB, 430, 362, 142, 20);
    Place(IDC_OUT_METER, L1, 384, 548, 34);
    Place(IDC_OUT_FORMAT, L1, 422, 548, 36);
    // One row, text vertically centred in the same 24-px band as the checkbox and the slider's middle.
    Place(IDC_L_MICVOL, L1, 462, 160, 24);  Place(IDC_MICVOL, 188, 460, 236, 28);
    Place(IDC_MICVOL_VALUE, 424, 462, 62, 24);
    Place(IDC_MICMUTE, 494, 462, 90, 24);

    Place(IDC_GROUP3, 12, 506, 576, 94);
    Place(IDC_L_SPKNAME, L1, 534, 94, 20);  Place(IDC_SPKNAME, C1, 530, 272, 23);
    Place(IDC_L_MICNAME, L1, 568, 94, 20);  Place(IDC_MICNAME, C1, 564, 272, 23);
    Place(IDC_RENAME, C2, 563, W2, 27);
    Place(IDC_IO_STATUS, L1, 606, 512, 300); // events (newest at the bottom, shown when closed)
    Place(IDC_CLEARLOG, 542, 604, 32, 26);   // clear the event log
    Place(IDC_AUTOSTART, L1, 638, 548, 22);  // start with Windows (in the tray)
    if (g_eventsWidest) FitEventList(nullptr);   // new DPI: text widths changed

    // Bottom row: settings file.
}

static void CreateControls()
{
    Create(L"BUTTON", TR(L"Качество сигнала кабеля"), BS_GROUPBOX, IDC_GROUP1);
    Create(L"STATIC", TR(L"Пресет:"), 0, IDC_L_PRESET);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP | WS_VSCROLL, IDC_PRESET);
    Create(L"STATIC", TR(L"Частота:"), 0, IDC_L_RATE);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP | WS_VSCROLL, IDC_RATE);
    Create(L"STATIC", TR(L"Разрядность:"), 0, IDC_L_BITS);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP, IDC_BITS);
    Create(L"STATIC", TR(L"Каналы:"), 0, IDC_L_CHANNELS);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP, IDC_CHANNELS);
    Create(L"BUTTON", TR(L"Проверка"), BS_PUSHBUTTON | WS_TABSTOP, IDC_TEST);
    Create(L"BUTTON", TR(L"Играть"), BS_PUSHBUTTON | WS_TABSTOP, IDC_PLAY);
    Create(L"STATIC", TR(L"Каналы микрофона:"), 0, IDC_L_MICCHANNELS);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP, IDC_MICCHANNELS);
    Create(L"STATIC", TR(L"Задержка, мс:"), 0, IDC_L_LATENCY);
    Create(L"EDIT", L"30", ES_NUMBER | WS_TABSTOP, IDC_LATENCY, WS_EX_CLIENTEDGE);
    Create(UPDOWN_CLASSW, L"", UDS_SETBUDDYINT | UDS_ALIGNRIGHT | UDS_ARROWKEYS | UDS_NOTHOUSANDS, IDC_LATENCY_UD);
    Create(L"BUTTON", TR(L"Применить"), BS_PUSHBUTTON | WS_TABSTOP, IDC_APPLY);
    Create(L"STATIC", L"", 0, IDC_SETTINGS_STATUS);

    Create(L"BUTTON", TR(L"Индикация сигнала"), BS_GROUPBOX, IDC_GROUP2);
    Create(L"STATIC", L"", 0, IDC_IN_LABEL);
    Create(L"STATIC", L"", SS_RIGHT, IDC_IN_DB);
    Create(L"S2mMeter", L"", 0, IDC_IN_METER);
    Create(L"STATIC", L"", 0, IDC_IN_FORMAT);
    Create(L"STATIC", L"", 0, IDC_OUT_LABEL);
    Create(L"STATIC", L"", SS_RIGHT, IDC_OUT_DB);
    Create(L"S2mMeter", L"", 0, IDC_OUT_METER);
    Create(L"STATIC", L"", 0, IDC_OUT_FORMAT);
    Create(L"STATIC", TR(L"Громкость микрофона:"), SS_CENTERIMAGE, IDC_L_MICVOL);
    Create(TRACKBAR_CLASSW, L"", TBS_HORZ | TBS_BOTTOM | WS_TABSTOP, IDC_MICVOL);
    Create(L"STATIC", L"", SS_RIGHT | SS_CENTERIMAGE, IDC_MICVOL_VALUE);
    Create(L"BUTTON", TR(L"Без звука"), BS_AUTOCHECKBOX | WS_TABSTOP, IDC_MICMUTE);
    SendMessageW(Ctl(IDC_MICVOL), TBM_SETRANGE, FALSE, MAKELPARAM(0, kMicMaxPercent));
    SendMessageW(Ctl(IDC_MICVOL), TBM_SETPAGESIZE, 0, 10);
    SendMessageW(Ctl(IDC_MICVOL), TBM_SETTIC, 0, 100);     // mark at 100 % = unchanged signal
    SendMessageW(Ctl(IDC_MICVOL), TBM_SETTIC, 0, 200);     // and at 200 % (0 and 300 % are the ends)
    Create(L"BUTTON", TR(L"Имена устройств"), BS_GROUPBOX, IDC_GROUP3);
    Create(L"STATIC", TR(L"Динамик:"), 0, IDC_L_SPKNAME);
    Create(L"EDIT", L"", ES_AUTOHSCROLL | WS_TABSTOP, IDC_SPKNAME, WS_EX_CLIENTEDGE);
    Create(L"STATIC", TR(L"Микрофон:"), 0, IDC_L_MICNAME);
    Create(L"EDIT", L"", ES_AUTOHSCROLL | WS_TABSTOP, IDC_MICNAME, WS_EX_CLIENTEDGE);
    Create(L"BUTTON", TR(L"Переименовать"), BS_PUSHBUTTON | WS_TABSTOP, IDC_RENAME);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP, IDC_IO_STATUS);     // event log
    Create(L"BUTTON", TR(L"Запускать панель управления вместе с Windows (в трее)"), BS_AUTOCHECKBOX | WS_TABSTOP, IDC_AUTOSTART);
    g_eventTip = CreateWindowExW(WS_EX_TOPMOST, TOOLTIPS_CLASSW, nullptr, WS_POPUP | TTS_ALWAYSTIP | TTS_NOPREFIX,
                                 CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, g_wnd, nullptr, g_inst, nullptr);
    if (g_eventTip)
    {
        TOOLINFOW ti = {};
        ti.cbSize = sizeof(ti);
        ti.uFlags = TTF_IDISHWND | TTF_SUBCLASS;
        ti.hwnd = g_wnd;
        ti.uId = (UINT_PTR)Ctl(IDC_IO_STATUS);
        ti.lpszText = LPSTR_TEXTCALLBACKW;
        SendMessageW(g_eventTip, TTM_ADDTOOLW, 0, (LPARAM)&ti);
        SendMessageW(g_eventTip, TTM_SETMAXTIPWIDTH, 0, 600);                // long events wrap
        SendMessageW(g_eventTip, TTM_SETDELAYTIME, TTDT_AUTOPOP, 30000);     // time to read
    }
    Create(L"BUTTON", TR(L"Очистить журнал событий"), BS_PUSHBUTTON | BS_ICON | WS_TABSTOP, IDC_CLEARLOG);
    SendMessageW(Ctl(IDC_SPKNAME), EM_LIMITTEXT, 60, 0);
    SendMessageW(Ctl(IDC_MICNAME), EM_LIMITTEXT, 60, 0);
    SendMessageW(Ctl(IDC_SPKNAME), EM_SETCUEBANNER, TRUE, (LPARAM)kDefaultName[0]);   // empty = default name
    SendMessageW(Ctl(IDC_MICNAME), EM_SETCUEBANNER, TRUE, (LPARAM)kDefaultName[1]);
    // Icon buttons (top left); the text stays the accessible name and is shown as a tooltip.
    Create(L"BUTTON", TR(L"Сбросить все настройки"), BS_PUSHBUTTON | BS_ICON | WS_TABSTOP, IDC_RESET_ALL);
    Create(L"BUTTON", TR(L"Экспорт настроек…"), BS_PUSHBUTTON | BS_ICON | WS_TABSTOP, IDC_EXPORT);
    Create(L"BUTTON", TR(L"Импорт настроек…"), BS_PUSHBUTTON | BS_ICON | WS_TABSTOP, IDC_IMPORT);
    Create(L"BUTTON", TR(L"Открыть микшер громкости"), BS_PUSHBUTTON | BS_ICON | WS_TABSTOP, IDC_MIXER);
    HWND tip = CreateWindowExW(WS_EX_TOPMOST, TOOLTIPS_CLASSW, nullptr, WS_POPUP | TTS_ALWAYSTIP | TTS_NOPREFIX,
                               CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, g_wnd, nullptr, g_inst, nullptr);
    const int tipIds[5] = { IDC_RESET_ALL, IDC_EXPORT, IDC_IMPORT, IDC_MIXER, IDC_CLEARLOG };
    const wchar_t* tipText[5] = { TR(L"Сбросить все настройки"), TR(L"Экспорт настроек…"), TR(L"Импорт настроек…"),
                                  TR(L"Открыть микшер громкости"), TR(L"Очистить журнал событий") };
    for (int i = 0; tip && i < 5; i++)
    {
        TOOLINFOW ti = {};
        ti.cbSize = sizeof(ti);
        ti.uFlags = TTF_IDISHWND | TTF_SUBCLASS;
        ti.hwnd = g_wnd;
        ti.uId = (UINT_PTR)Ctl(tipIds[i]);
        ti.lpszText = (LPWSTR)tipText[i];
        SendMessageW(tip, TTM_ADDTOOLW, 0, (LPARAM)&ti);
    }
    ApplyToolIcons();
    Create(L"STATIC", TR(L"Язык:"), SS_RIGHT, IDC_L_LANG);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP | WS_VSCROLL, IDC_LANG);
    LangFillCombo(Ctl(IDC_LANG));


    for (auto& p : kPresets) ComboAdd(IDC_PRESET, p.name, 0);
    for (DWORD r : kRates)
    {
        wchar_t t[32];
        _snwprintf(t, 32, TR(L"%lu Гц"), r);
        ComboAdd(IDC_RATE, t, r);
    }
    for (int i = 0; i < 4; i++) ComboAdd(IDC_BITS, kBitsNames[i], kBits[i]);
    for (int i = 0; i < 5; i++) ComboAdd(IDC_CHANNELS, kChannelNames[i], kChannels[i]);
    ComboAdd(IDC_MICCHANNELS, TR(L"Как у динамика"), 0);
    for (int i = 0; i < 5; i++) ComboAdd(IDC_MICCHANNELS, kChannelNames[i], kChannels[i]);
    SendMessageW(Ctl(IDC_LATENCY_UD), UDM_SETRANGE32, 10, 500);
    if (!g_elevated)
    {
        SendMessageW(Ctl(IDC_APPLY), BCM_SETSHIELD, 0, TRUE);
    }
}

// ---------------------------------------------------------------------------
// Settings UI

static void SyncPreset()
{
    DWORD rate = (DWORD)ComboData(IDC_RATE), bits = (DWORD)ComboData(IDC_BITS), ch = (DWORD)ComboData(IDC_CHANNELS);
    int sel = 0;
    for (int i = 1; i < (int)(sizeof(kPresets) / sizeof(kPresets[0])); i++)
    {
        if (kPresets[i].rate == rate && kPresets[i].bits == bits && kPresets[i].channels == ch) sel = i;
    }
    SendMessageW(Ctl(IDC_PRESET), CB_SETCURSEL, sel, 0);
}

static Settings SettingsFromControls();

// "Apply" is enabled only while the chosen signal quality differs from what the driver runs with.
static void UpdateApplyButton()
{
    Settings s = SettingsFromControls();
    bool changed = s.rate != g_settings.rate || s.bits != g_settings.bits || s.channels != g_settings.channels ||
                   s.micChannels != g_settings.micChannels ||
                   s.latency != g_settings.latency;
    EnableWindow(Ctl(IDC_APPLY), g_driverInstalled && changed);
}

static void ShowSettings(const Settings& s)
{
    g_updatingControls = true;
    ComboSelectData(IDC_RATE, s.rate);
    ComboSelectData(IDC_BITS, s.bits);
    ComboSelectData(IDC_CHANNELS, s.channels);
    ComboSelectData(IDC_MICCHANNELS, s.micChannels);
    SendMessageW(Ctl(IDC_LATENCY_UD), UDM_SETPOS32, 0, s.latency);
    SyncPreset();
    g_updatingControls = false;
    UpdateApplyButton();
}

static void ShowDriverStatus()
{
    wchar_t t[256];
    if (!g_driverInstalled)
    {
        wcscpy(t, TR(L"Драйвер Speak2Mic не установлен: настройки применить нельзя."));
    }
    else
    {
        wchar_t bits[32];
        if (g_settings.bits) _snwprintf(bits, 32, TR(L"%lu бит"), g_settings.bits);
        else wcscpy(bits, TR(L"16–32 бит"));
        _snwprintf(t, 256, TR(L"Сейчас в драйвере: %lu Гц · %ls · до %lu кан. · задержка %lu мс"),
                   g_settings.rate, bits, g_settings.channels, g_settings.latency);
    }
    t[255] = 0;
    SetText(IDC_SETTINGS_STATUS, t);
    UpdateApplyButton();
}

static Settings SettingsFromControls()
{
    Settings s;
    s.rate = (DWORD)ComboData(IDC_RATE);
    s.bits = (DWORD)ComboData(IDC_BITS);
    s.channels = (DWORD)ComboData(IDC_CHANNELS);
    s.micChannels = (DWORD)ComboData(IDC_MICCHANNELS);
    BOOL err = FALSE;
    int lat = (int)SendMessageW(Ctl(IDC_LATENCY_UD), UDM_GETPOS32, 0, (LPARAM)&err);
    s.latency = (DWORD)(err ? 30 : (lat < 10 ? 10 : (lat > 500 ? 500 : lat)));
    return s;
}

// ---------------------------------------------------------------------------
// Devices, meters

static bool NameHas(const wchar_t* name, const wchar_t* part)
{
    size_t n = wcslen(part);
    for (; *name; name++)
        if (_wcsnicmp(name, part, n) == 0) return true;
    return false;
}

// Our endpoints are recognized by their adapter ("Speak2Mic"), not by their name: the user may rename them.
static bool IsOurDevice(const AudioDevice& d)
{
    return d.adapter[0] ? _wcsicmp(d.adapter, L"Speak2Mic") == 0 : NameHas(d.name, L"(Speak2Mic)");
}

// The playback side of the cable (input = true, "Speak2Mic Speaker") or the microphone.
static int FindInList(const AudioDevice* list, int count, bool input)
{
    for (int i = 0; i < count; i++)
    {
        if (list[i].flow == (input ? eRender : eCapture) && IsOurDevice(list[i])) return i;
    }
    return -1;
}

static int FindCableDevice(bool input)
{
    return FindInList(g_devs, g_devCount, input);
}

static void StartMeters()
{
    g_meterIn.Stop();
    g_meterOut.Stop();
    ClearMeter(Ctl(IDC_IN_METER));
    ClearMeter(Ctl(IDC_OUT_METER));

    int in = FindCableDevice(true), out = FindCableDevice(false);
    wchar_t t[400];
    _snwprintf(t, 400, TR(L"%ls — воспроизведение (сюда играют программы)"),
               in >= 0 && g_devs[in].desc[0] ? g_devs[in].desc : kDefaultName[0]);
    t[399] = 0;
    SetText(IDC_IN_LABEL, t);
    _snwprintf(t, 400, TR(L"%ls — микрофон (это слышат программы записи)"),
               out >= 0 && g_devs[out].desc[0] ? g_devs[out].desc : kDefaultName[1]);
    t[399] = 0;
    SetText(IDC_OUT_LABEL, t);

    g_inFound = in >= 0;
    g_outFound = out >= 0;
    AppLog(L"meters: speaker %ls, mic %ls", g_inFound ? L"found" : L"NOT found",
           g_outFound ? L"found" : L"NOT found");
    if (g_inFound) g_meterIn.Start(g_devs[in]);
    if (g_outFound) g_meterOut.Start(g_devs[out]);
}

static void StopMeters()
{
    g_meterIn.Stop();
    g_meterOut.Stop();
}

// True when a Speak2Mic endpoint the meters are missing is now active (checked without logging).
static bool SpeakDevicesAppeared()
{
    static AudioDevice list[128];
    int n = ListAudioDevices(list, 128);
    for (int i = 0; i < n; i++)
    {
        if (!g_inFound && list[i].flow == eRender && IsOurDevice(list[i])) return true;
        if (!g_outFound && list[i].flow == eCapture && IsOurDevice(list[i])) return true;
    }
    return false;
}

// ---------------------------------------------------------------------------
// Microphone volume (the Windows endpoint volume of "Speak2Mic Microphone", as in its "Levels" tab)

// The slider is the signal level in percent of amplitude: 100 % = 0 dB (the cable's signal unchanged),
// 50 % = -6 dB, up to 300 % = +9.5 dB of boost; 0 % = the endpoint's minimum (silence). The driver's volume
// node has exactly that range (-96..+9.56 dB), so Windows' own "100 %" is the panel's 300 %. Drivers before
// 1.0.272 had no node: Windows used -96..+30 dB software volume, and stronger gain set elsewhere shows its real
// percentage next to the slider (which then sits at 300 %).
static int g_micVolShown = -1;      // volume shown, in 0.1 dB steps (+ 100000 offset); -1 = no microphone
static int g_micMuteShown = -1;     // mute state shown, -1 = unknown

// The volume chosen in the panel (slider, import, reset) is remembered: Windows may put this microphone back
// to its maximum (its own "100 %") when the endpoint is (re)created, e.g. after a device restart.
static void SaveMicVolume(float db)
{
    HKEY key;
    if (RegCreateKeyExW(HKEY_CURRENT_USER, S2M_USER_KEY, 0, nullptr, 0, KEY_SET_VALUE, nullptr, &key, nullptr) != ERROR_SUCCESS)
        return;
    DWORD centi = (DWORD)(LONG)floorf(db * 100.0f + 0.5f);     // hundredths of a dB, signed
    RegSetValueExW(key, L"MicVolumeCentiDb", 0, REG_DWORD, (const BYTE*)&centi, sizeof(centi));
    RegCloseKey(key);
}

static float LoadMicVolume()
{
    DWORD centi = 0, size = sizeof(centi);
    if (RegGetValueW(HKEY_CURRENT_USER, S2M_USER_KEY, L"MicVolumeCentiDb", RRF_RT_REG_DWORD, nullptr, &centi, &size) != ERROR_SUCCESS)
        return 0.0f;            // nothing chosen yet: unity gain
    return (LONG)centi / 100.0f;
}

static int DbToPercent(float db)
{
    // The top step of the driver's volume node (+9.5625 dB on its 1/16 dB grid) is exactly 300 % (gain x3.0).
    if (db > 9.53f && db < 9.60f) return 300;
    int pct = (int)(100.0f * powf(10.0f, db / 20.0f) + 0.5f);
    return pct < 0 ? 0 : pct;
}

static void ShowMicVolumeValue(float db)
{
    wchar_t t[32];
    _snwprintf(t, 32, L"%d %%", DbToPercent(db));
    t[31] = 0;
    SetText(IDC_MICVOL_VALUE, t);
}

// Reads the current volume and mute state (they may also be changed in Sound settings) unless the user
// drags the slider.
static void SyncMicVolume()
{
    int i = FindCableDevice(false);
    float db = 0, mn = 0, mx = 0;
    bool ok = i >= 0 && GetEndpointVolumeDb(g_devs[i].id, &db, &mn, &mx);
    bool mute = false;
    bool muteOk = i >= 0 && GetEndpointMute(g_devs[i].id, &mute);
    EnableWindow(Ctl(IDC_MICVOL), ok);
    EnableWindow(Ctl(IDC_MICMUTE), muteOk);
    int muteKey = muteOk ? (mute ? 1 : 0) : -1;
    if (muteKey != g_micMuteShown)
    {
        g_micMuteShown = muteKey;
        SendMessageW(Ctl(IDC_MICMUTE), BM_SETCHECK, mute ? BST_CHECKED : BST_UNCHECKED, 0);
    }
    if (ok && mx > 20.0f && db >= mx - 0.05f)
    {
        // Old driver (software volume up to +30 dB) at Windows' maximum: the endpoint was reset (the panel never
        // goes above +9.5 dB). With the driver's volume node the maximum is the panel's own 300 %.
        float want = LoadMicVolume();
        if (want < mx - 0.05f && SetEndpointVolumeDb(g_devs[i].id, want))
        {
            AppLog(L"microphone volume was at the Windows maximum (%.1f dB): restored %.1f dB", db, want);
            GetEndpointVolumeDb(g_devs[i].id, &db, &mn, &mx);
        }
    }
    int key = ok ? 100000 + (int)floorf(db * 10.0f + 0.5f) : -1;
    if (key == g_micVolShown || GetCapture() == Ctl(IDC_MICVOL)) return;
    g_micVolShown = key;
    if (!ok)
    {
        SetText(IDC_MICVOL_VALUE, L"—");
        return;
    }
    int pct = DbToPercent(db);
    SendMessageW(Ctl(IDC_MICVOL), TBM_SETPOS, TRUE, pct > kMicMaxPercent ? kMicMaxPercent : pct);
    ShowMicVolumeValue(db);
}

static void OnMicVolumeSlider(int code)
{
    int i = FindCableDevice(false);
    if (i < 0) return;
    int pct = (int)SendMessageW(Ctl(IDC_MICVOL), TBM_GETPOS, 0, 0);
    // Dragging with the mouse snaps to 0, 100, 200 and 300 % within 5 % of them (the keyboard moves freely: arrow
    // keys step by 1 and would never get past a snap point).
    if (code == TB_THUMBTRACK || code == TB_THUMBPOSITION)
    {
        static const int snaps[4] = { 0, 100, 200, 300 };
        for (int s : snaps)
        {
            if (pct != s && abs(pct - s) <= 5)
            {
                pct = s;
                SendMessageW(Ctl(IDC_MICVOL), TBM_SETPOS, TRUE, pct);
                break;
            }
        }
    }
    float db = pct > 0 ? 20.0f * log10f(pct / 100.0f) : -200.0f;     // -200: clamped to the minimum
    if (SetEndpointVolumeDb(g_devs[i].id, db))
    {
        float now = 0, mn = 0, mx = 0;
        if (GetEndpointVolumeDb(g_devs[i].id, &now, &mn, &mx))
        {
            g_micVolShown = 100000 + (int)floorf(now * 10.0f + 0.5f);
            ShowMicVolumeValue(now);
        }
        SaveMicVolume(db < mn ? mn : db);
    }
}

// ---------------------------------------------------------------------------
// Protection (always on while the panel runs): a change of the microphone volume made by another program (not by a Speak2Mic
// program: those mark their changes) is set back to the volume chosen here (MicVolumeCentiDb).

#define WM_APP_FOREIGN_VOLUME (WM_APP + 23)
static void*   g_micWatch;
static wchar_t g_micWatchId[256];
static DWORD   g_protectLogged;         // GetTickCount of the last event log line about it
static int     g_protectCount;          // set back since that line

static void OnForeignMicVolumeThread(float db, float, bool, const GUID&, void*)
{
    // system thread: hand it to the window (hundredths of a dB)
    PostMessageW(g_wnd, WM_APP_FOREIGN_VOLUME, (WPARAM)(LONG_PTR)(LONG)floorf(db * 100.0f + 0.5f), 0);
}

// Watches the current microphone (it changes after "Apply": the endpoint is recreated).
static void EnsureMicWatch()
{
    int i = FindCableDevice(false);
    const wchar_t* id = i >= 0 ? g_devs[i].id : L"";
    if (wcscmp(id, g_micWatchId) == 0 && (g_micWatch || !*id)) return;
    UnwatchEndpointVolume(g_micWatch);
    g_micWatch = *id ? WatchEndpointVolume(id, OnForeignMicVolumeThread, nullptr) : nullptr;
    wcsncpy(g_micWatchId, id, 255);
    g_micWatchId[255] = 0;
}

static void OnForeignMicVolume(float db)
{
    int i = FindCableDevice(false);
    if (i < 0) return;
    float want = LoadMicVolume(), now = 0, mn = 0, mx = 0;
    if (!GetEndpointVolumeDb(g_devs[i].id, &now, &mn, &mx) || fabsf(now - want) < 0.05f) return;   // already back
    if (!SetEndpointVolumeDb(g_devs[i].id, want)) return;
    {
        wchar_t who[300];
        ActiveSessionPrograms(g_devs[i].id, who, 300);
        AppLog(L"microphone volume changed by another program to %.2f dB: set back to %.2f dB (active sessions: %ls)", db, want,
               who[0] ? who : L"none");
    }
    g_protectCount++;
    DWORD t = GetTickCount();
    if (t - g_protectLogged >= 5000 || !g_protectLogged)
    {
        // the event list gets at most one line per 5 s (some programs change it all the time)
        // Who: the programs holding an active session on the microphone (a volume change itself carries no
        // program; call / monitoring programs that adjust the level keep the microphone open).
        wchar_t who[300], line[480];
        ActiveSessionPrograms(g_devs[i].id, who, 300);
        if (who[0])
            _snwprintf(line, 480, TR(L"Громкость микрофона изменила программа %ls (%d %%) — возвращено %d %% (раз: %d)."), who,
                       DbToPercent(db), DbToPercent(want), g_protectCount);
        else
            _snwprintf(line, 480, TR(L"Громкость микрофона изменила другая программа (%d %%) — возвращено %d %% (раз: %d)."),
                       DbToPercent(db), DbToPercent(want), g_protectCount);
        line[479] = 0;
        AddEvent(line);
        g_protectLogged = t ? t : 1;
        g_protectCount = 0;
    }
    g_micVolShown = -1;
    SyncMicVolume();
}

static void OnMicMute()
{
    int i = FindCableDevice(false);
    if (i < 0) return;
    bool mute = SendMessageW(Ctl(IDC_MICMUTE), BM_GETCHECK, 0, 0) == BST_CHECKED;
    if (SetEndpointMute(g_devs[i].id, mute)) g_micMuteShown = mute ? 1 : 0;
    AppLog(L"microphone mute: %ls", mute ? L"on" : L"off");
}

// ---------------------------------------------------------------------------
// Sound test ("Test" in Windows' speaker properties): the Windows sound on every speaker channel in turn

#define WM_APP_TEST_DONE (WM_APP + 20)
static HANDLE        g_testThread;
static volatile LONG g_testStop;
static wchar_t       g_testDevice[256];

static DWORD WINAPI TestThread(LPVOID)
{
    HRESULT hr = PlayChannelTest(g_testDevice, &g_testStop);
    PostMessageW(g_wnd, WM_APP_TEST_DONE, (WPARAM)hr, 0);
    return 0;
}

static void StopTest()
{
    if (!g_testThread) return;
    InterlockedExchange(&g_testStop, 1);
    WaitForSingleObject(g_testThread, 3000);
    CloseHandle(g_testThread);
    g_testThread = nullptr;
    SetText(IDC_TEST, TR(L"Проверка"));
}

static void OnTest()
{
    if (g_testThread)
    {
        StopTest();
        AddEvent(TR(L"Проверка звука остановлена."));
        return;
    }
    int i = FindCableDevice(true);
    if (i < 0) return;
    wcsncpy(g_testDevice, g_devs[i].id, 255);
    g_testDevice[255] = 0;
    g_testStop = 0;
    g_testThread = CreateThread(nullptr, 0, TestThread, nullptr, 0, nullptr);
    if (g_testThread)
    {
        SetText(IDC_TEST, TR(L"Стоп"));
        AddEvent(TR(L"Проверка звука запущена."));
    }
    AppLog(L"sound test started on \"%ls\"", g_devs[i].name);
}

static void OnTestDone(HRESULT hr)
{
    if (g_testThread)
    {
        WaitForSingleObject(g_testThread, 3000);
        CloseHandle(g_testThread);
        g_testThread = nullptr;
    }
    SetText(IDC_TEST, TR(L"Проверка"));
    if (FAILED(hr))
    {
        wchar_t t[160];
        _snwprintf(t, 160, TR(L"Проверка звука не удалась (0x%08lX)."), (unsigned long)hr);
        t[159] = 0;
        AddEvent( t);
    }
    else AddEvent(TR(L"Проверка звука завершена."));
}

// ---------------------------------------------------------------------------
// Music: the .mp3 files of the "mp3" folder next to the program (C:\Program Files\Speak2Mic\mp3), in random
// order, on "Speak2Mic Speaker". The folder is read again on every track and on every "Play".

#define WM_APP_PLAY_DONE (WM_APP + 21)
#define WM_APP_PLAY_TRACK (WM_APP + 22)    // lParam = file name (malloc)

static void Mp3Folder(wchar_t* folder)
{
    Mp3DefaultFolder(folder);
}

// "Play" without files in the folder is disabled; while playing it is "Pause".
static void UpdatePlayButton()
{
    wchar_t folder[MAX_PATH];
    Mp3Folder(folder);
    bool playing = Mp3Playing();
    SetText(IDC_PLAY, playing ? TR(L"Пауза") : TR(L"Играть"));
    EnableWindow(Ctl(IDC_PLAY), playing || Mp3FolderHasFiles(folder));
}

static void StopMusic()
{
    Mp3Pause();
    UpdatePlayButton();
}

static void OnPlay()
{
    if (Mp3Playing())
    {
        StopMusic();
        const wchar_t* track = wcsrchr(Mp3LastFile(), L'\\');
        wchar_t t[400];
        _snwprintf(t, 400, TR(L"Музыка: пауза (%ls)."), track ? track + 1 : Mp3LastFile());
        t[399] = 0;
        AddEvent(t);
        return;
    }
    wchar_t folder[MAX_PATH];
    Mp3Folder(folder);
    int i = FindCableDevice(true);
    if (i >= 0 && Mp3Play(g_devs[i].id, folder, g_wnd, WM_APP_PLAY_DONE, WM_APP_PLAY_TRACK))
    {
        const wchar_t* track = wcsrchr(Mp3LastFile(), L'\\');
        wchar_t t[400];
        _snwprintf(t, 400, TR(L"Музыка: воспроизведение (%ls)."), track ? track + 1 : Mp3LastFile());
        t[399] = 0;
        AddEvent(t);
    }
    else AppLog(L"mp3: nothing to play in %ls", folder);
    UpdatePlayButton();
}

static void OnPlayDone(HRESULT hr)
{
    Mp3Pause();                             // the thread has ended: release it
    if (FAILED(hr))
    {
        wchar_t t[160];
        _snwprintf(t, 160, TR(L"Не удалось воспроизвести mp3 (0x%08lX)."), (unsigned long)hr);
        t[159] = 0;
        AddEvent(t);
    }
    else if (hr == S_FALSE) AddEvent(TR(L"Музыка остановлена: в папке нет mp3-файлов."));
    UpdatePlayButton();
}

// ---------------------------------------------------------------------------
// Device names

static void RefreshDevices(bool startMeters = true);

static wchar_t g_shownName[2][256];     // names put into the edit boxes (current endpoint names)

static void GetEditName(int id, wchar_t* out, size_t len)
{
    wchar_t raw[256];
    GetWindowTextW(Ctl(id), raw, 256);
    const wchar_t* b = raw;
    while (*b == L' ' || *b == L'\t') b++;
    size_t n = wcslen(b);
    while (n && (b[n - 1] == L' ' || b[n - 1] == L'\t')) n--;
    if (n >= len) n = len - 1;
    wmemcpy(out, b, n);
    out[n] = 0;
    for (wchar_t* c = out; *c; c++)
        if (*c == L'"') *c = L'\'';    // keeps the elevated command line simple
}

// Enabled only while a name box differs from the endpoint's current name.
static void UpdateRenameButton()
{
    bool changed = false;
    const int ids[2] = { IDC_SPKNAME, IDC_MICNAME };
    for (int side = 0; side < 2; side++)
    {
        if (FindCableDevice(side == 0) < 0) continue;
        wchar_t want[256];
        GetEditName(ids[side], want, 256);
        if (!want[0]) wcscpy(want, kDefaultName[side]);
        if (wcscmp(want, g_shownName[side]) != 0) changed = true;
    }
    EnableWindow(Ctl(IDC_RENAME), changed);
}

// Puts the current endpoint names into the edit boxes (unless the user is editing them).
static void ShowNames()
{
    const int ids[2] = { IDC_SPKNAME, IDC_MICNAME };
    for (int side = 0; side < 2; side++)
    {
        int i = FindCableDevice(side == 0);
        const wchar_t* name = i >= 0 && g_devs[i].desc[0] ? g_devs[i].desc : kDefaultName[side];
        wchar_t cur[256];
        GetEditName(ids[side], cur, 256);
        bool untouched = !cur[0] || wcscmp(cur, g_shownName[side]) == 0;
        wcsncpy(g_shownName[side], name, 255);
        g_shownName[side][255] = 0;
        if (untouched)
        {
            g_updatingControls = true;
            SetWindowTextW(Ctl(ids[side]), name);
            g_updatingControls = false;
        }
        EnableWindow(Ctl(ids[side]), i >= 0);
    }
    UpdateRenameButton();
}

static void SaveName(int side, const wchar_t* name)
{
    HKEY key;
    if (RegCreateKeyExW(HKEY_CURRENT_USER, S2M_USER_KEY, 0, nullptr, 0, KEY_SET_VALUE, nullptr, &key, nullptr) != ERROR_SUCCESS)
        return;
    const wchar_t* value = side == 0 ? L"SpeakerName" : L"MicName";
    if (wcscmp(name, kDefaultName[side]) == 0)
        RegDeleteValueW(key, value);
    else
        RegSetValueExW(key, value, 0, REG_SZ, (const BYTE*)name, (DWORD)((wcslen(name) + 1) * sizeof(wchar_t)));
    RegCloseKey(key);
}

static bool LoadName(int side, wchar_t* out, DWORD len)
{
    DWORD size = len * sizeof(wchar_t);
    return RegGetValueW(HKEY_CURRENT_USER, S2M_USER_KEY, side == 0 ? L"SpeakerName" : L"MicName", RRF_RT_REG_SZ,
                        nullptr, out, &size) == ERROR_SUCCESS && out[0];
}

// Renames through an elevated copy of the panel (Windows may refuse the change without admin rights).
static HRESULT RenameElevated(HWND hwnd, int side, const wchar_t* name)
{
    wchar_t exe[MAX_PATH], args[400];
    GetModuleFileNameW(nullptr, exe, MAX_PATH);
    _snwprintf(args, 400, L"--rename %ls \"%ls\"", side == 0 ? L"speaker" : L"mic", name);
    args[399] = 0;
    SHELLEXECUTEINFOW sei = {};
    sei.cbSize = sizeof(sei);
    sei.fMask = SEE_MASK_NOCLOSEPROCESS;
    sei.hwnd = hwnd;
    sei.lpVerb = L"runas";
    sei.lpFile = exe;
    sei.lpParameters = args;
    sei.nShow = SW_HIDE;
    if (!ShellExecuteExW(&sei) || !sei.hProcess) return HRESULT_FROM_WIN32(ERROR_CANCELLED);
    WaitForSingleObject(sei.hProcess, 30000);
    DWORD code = (DWORD)E_FAIL;
    GetExitCodeProcess(sei.hProcess, &code);
    CloseHandle(sei.hProcess);
    return (HRESULT)code;
}

static HRESULT RenameSide(int side, const wchar_t* name, bool allowElevation)
{
    int i = FindCableDevice(side == 0);
    if (i < 0) return E_NOTFOUND;
    HRESULT hr = SetEndpointName(g_devs[i].id, name);
    AppLog(L"rename %ls \"%ls\" -> \"%ls\": 0x%08lX", side == 0 ? L"speaker" : L"mic", g_devs[i].desc, name,
           (unsigned long)hr);
    if (FAILED(hr) && allowElevation && !g_elevated)
    {
        hr = RenameElevated(g_wnd, side, name);
        AppLog(L"rename %ls (elevated): 0x%08lX", side == 0 ? L"speaker" : L"mic", (unsigned long)hr);
    }
    return hr;
}

static void OnRename()
{
    const int ids[2] = { IDC_SPKNAME, IDC_MICNAME };
    HRESULT result = S_OK;
    bool any = false;
    for (int side = 0; side < 2; side++)
    {
        if (FindCableDevice(side == 0) < 0) continue;
        wchar_t want[256];
        GetEditName(ids[side], want, 256);
        if (!want[0]) wcscpy(want, kDefaultName[side]);       // empty = back to the default name
        if (wcscmp(want, g_shownName[side]) == 0) continue;
        any = true;
        HRESULT hr = RenameSide(side, want, true);
        if (SUCCEEDED(hr))
        {
            SaveName(side, want);
            g_updatingControls = true;
            SetWindowTextW(Ctl(ids[side]), want);
            g_updatingControls = false;
        }
        else
        {
            result = hr;
        }
    }
    if (!any) return;
    wchar_t t[200];
    if (SUCCEEDED(result)) wcscpy(t, TR(L"Имена изменены."));
    else _snwprintf(t, 200, TR(L"Не удалось переименовать (0x%08lX)."), (unsigned long)result);
    t[199] = 0;
    AddEvent( t);
    g_shownName[0][0] = g_shownName[1][0] = 0;      // take the new names from Windows
    RefreshDevices();
}

// After a reinstall Windows may bring the endpoints back with their default names: put the user's back.
static void RestoreSavedNames()
{
    bool renamed = false;
    for (int side = 0; side < 2; side++)
    {
        int i = FindCableDevice(side == 0);
        wchar_t saved[256];
        // The microphone's default name used to be "Speak2Mic Mic": Windows keeps an existing endpoint's name
        // across a driver update, so an untouched old default is moved to the new one.
        if (i >= 0 && side == 1 && !LoadName(side, saved, 256) && wcscmp(g_devs[i].desc, L"Speak2Mic Mic") == 0)
        {
            if (SUCCEEDED(RenameSide(side, kDefaultName[side], false))) renamed = true;
            continue;
        }
        if (i < 0 || !LoadName(side, saved, 256)) continue;
        if (wcscmp(g_devs[i].desc, kDefaultName[side]) != 0 || wcscmp(saved, kDefaultName[side]) == 0) continue;
        if (SUCCEEDED(RenameSide(side, saved, false))) renamed = true;
    }
    if (renamed) RefreshDevices();
}

// startMeters = false: the caller sets the endpoint formats first (after "Apply" the stored format
// still has the old sample rate and the meters would fail with AUDCLNT_E_UNSUPPORTED_FORMAT meanwhile).
static void RefreshDevices(bool startMeters)
{
    StopMeters();
    g_devCount = ListAudioDevices(g_devs, 128);
    AudioDevice defaultRender;
    bool hasDefault = GetDefaultRenderDevice(&defaultRender);
    // Logged only when the list changed (the meters reconnect every few seconds while a device is broken).
    static unsigned long lastHash = 0;
    unsigned long hash = 5381;
    for (int i = 0; i < g_devCount; i++)
        for (const wchar_t* c = g_devs[i].name; *c; c++) hash = hash * 33 + *c;
    for (const wchar_t* c = hasDefault ? defaultRender.name : L""; *c; c++) hash = hash * 33 + *c;
    if (hash != lastHash)
    {
        lastHash = hash;
        AppLog(L"devices: %d active audio endpoint(s), default playback: %ls", g_devCount,
               hasDefault ? defaultRender.name : L"(none)");
        for (int i = 0; i < g_devCount; i++)
        {
            AppLog(L"  %ls: %ls", g_devs[i].flow == eRender ? L"playback" : L"recording", g_devs[i].name);
        }
    }

    ShowNames();
    g_micVolShown = -2;     // force a re-read
    g_micMuteShown = -2;
    SyncMicVolume();
    if (startMeters) StartMeters();
}

static void UpdateMeterUi(LevelMeter& m, bool found, int meterId, int dbId, int fmtId)
{
    float peaks[S2M_MAX_METER_CHANNELS];
    int n = found ? m.TakePeaks(peaks, S2M_MAX_METER_CHANNELS) : 0;
    wchar_t t[160];
    if (!found)
    {
        ClearMeter(Ctl(meterId));
        SetText(dbId, L"—");
        SetText(fmtId, TR(L"Устройство не найдено: драйвер не установлен или перезапускается."));
        return;
    }
    float level = n ? UpdateMeter(Ctl(meterId), peaks, n) : 0;
    if (level < 0.001f)
        wcscpy(t, TR(L"нет сигнала"));
    else
        _snwprintf(t, 160, TR(L"%.1f дБ"), 20.0f * log10f(level));
    SetText(dbId, t);
    m.GetStatus(t, 160);
    wchar_t cur[160];
    GetWindowTextW(Ctl(fmtId), cur, 160);
    if (wcscmp(cur, t) != 0)
    {
        AppLog(L"meter %ls: %ls", meterId == IDC_IN_METER ? L"speaker" : L"mic", t);
        if (wcsstr(t, L"0x") && g_driverLogMark[0]) DumpDriverLog(L"meter error");
    }
    SetText(fmtId, t);
}

// ---------------------------------------------------------------------------
// Driver log -> panel.log

static void MarkDriverLog()
{
    SYSTEMTIME t;
    GetLocalTime(&t);
    _snwprintf(g_driverLogMark, 32, L"%04u-%02u-%02u %02u:%02u:%02u.%03u", t.wYear, t.wMonth, t.wDay, t.wHour,
               t.wMinute, t.wSecond, t.wMilliseconds);
    g_driverLogMark[31] = 0;
}

// Copies the driver log lines written after g_driverLogMark into panel.log.
static void DumpDriverLog(const wchar_t* reason)
{
    DWORD size = 0;
    if (RegGetValueW(HKEY_LOCAL_MACHINE, S2M_PARAMS_KEY, L"DriverLog", RRF_RT_REG_SZ, nullptr, nullptr, &size) != ERROR_SUCCESS ||
        !size)
        return;
    wchar_t* text = (wchar_t*)HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, size + 2);
    if (!text) return;
    if (RegGetValueW(HKEY_LOCAL_MACHINE, S2M_PARAMS_KEY, L"DriverLog", RRF_RT_REG_SZ, nullptr, text, &size) == ERROR_SUCCESS)
    {
        AppLog(L"---- driver log since %ls (%ls) ----", g_driverLogMark, reason);
        for (wchar_t* line = text; *line;)
        {
            wchar_t* end = line;
            while (*end && *end != L'\r' && *end != L'\n') end++;
            wchar_t saved = *end;
            *end = 0;
            if (wcslen(line) >= 23 && wcsncmp(line, g_driverLogMark, 23) > 0)
            {
                AppLog(L"[driver] %ls", line);
                wcsncpy(g_driverLogMark, line, 23);     // next dump starts after this line
                g_driverLogMark[23] = 0;
            }
            *end = saved;
            while (*end == L'\r' || *end == L'\n') end++;
            line = end;
        }
    }
    HeapFree(GetProcessHeap(), 0, text);
}

// ---------------------------------------------------------------------------
// Default format of the endpoints

// Puts the chosen format on "Speak2Mic Speaker" and "Speak2Mic Microphone" as the Windows default
// format. Returns true when done (or impossible), false to try again later.
static bool ApplyEndpointFormats()
{
    const Settings& s = g_formatTarget;
    WORD bits = (WORD)(s.bits ? s.bits : 24);
    int done = 0, missing = 0, failed = 0, fellBack = 0;
    wchar_t lastErr[160] = L"";

    {
        for (int side = 0; side < 2; side++)
        {
            int i = FindCableDevice(side == 0);
            if (i < 0)
            {
                missing++;
                continue;
            }
            // The microphone may have its own channel count (0 = as the speaker).
            DWORD ch = side == 0 || !s.micChannels ? s.channels : s.micChannels;
            if (g_formatOnlyIfWrong)
            {
                DWORD r = 0;
                WORD b = 0, c = 0;
                // Bit depth is not compared: Windows may not accept 24/32 bits, then 16 bits is used.
                if (GetEndpointFormat(g_devs[i].id, &r, &b, &c) && r == s.rate && c <= ch)
                {
                    continue;   // still valid for the driver
                }
                AppLog(L"default format of \"%ls\" (%lu Hz %u bit %u ch) does not match the driver settings",
                       g_devs[i].name, r, b, c);
            }
            wchar_t err[160];
            bool ok = SetEndpointFormat(g_devs[i].id, s.rate, bits, (WORD)ch, err, 160);
            if (!ok && bits > 16)
            {
                // Windows does not always take 24/32-bit integer formats; 16 bits at the chosen rate
                // keeps the endpoint working.
                AppLog(L"default format of \"%ls\": %u bit refused (%ls), falling back to 16 bit", g_devs[i].name, bits, err);
                ok = SetEndpointFormat(g_devs[i].id, s.rate, 16, (WORD)ch, err, 160);
                if (ok) fellBack++;
            }
            if (ok)
            {
                DWORD r = 0;
                WORD b = 0, c = 0;
                GetEndpointFormat(g_devs[i].id, &r, &b, &c);
                AppLog(L"default format of \"%ls\": set %lu Hz %u bit %lu ch (%ls), now %lu Hz %u bit %u ch",
                       g_devs[i].name, s.rate, bits, ch, err, r, b, c);
                done++;
            }
            else
            {
                DWORD r = 0;
                WORD b = 0, c = 0;
                GetEndpointFormat(g_devs[i].id, &r, &b, &c);
                AppLog(L"default format of \"%ls\": %ls; now %lu Hz %u bit %u ch", g_devs[i].name, err, r, b, c);
                wcscpy(lastErr, err);
                failed++;
            }
        }
    }

    if (missing && --g_formatTries > 0)
    {
        return false;   // endpoints not back yet
    }
    AppLog(L"default formats: %d set, %d failed, %d endpoint(s) missing", done, failed, missing);
    DumpDriverLog(L"after applying settings");

    if (g_formatOnlyIfWrong && !done && !failed)
    {
        return true;    // startup check: nothing to fix
    }
    wchar_t t[300];
    if (failed)
        _snwprintf(t, 300, TR(L"Формат по умолчанию установлен не для всех устройств Speak2Mic: %ls"), lastErr);
    else if (missing && !done)
        _snwprintf(t, 300, TR(L"Устройства Speak2Mic не появились после перезапуска — формат по умолчанию не установлен."));
    else if (fellBack)
        _snwprintf(t, 300, TR(L"Настройки применены: %lu Гц, %lu кан. Windows не приняла %u бит — формат по умолчанию 16 бит."),
                   s.rate, s.channels, bits);
    else
        _snwprintf(t, 300, TR(L"Настройки применены: формат по умолчанию %lu Гц, %u бит, %lu кан."), s.rate, bits, s.channels);
    t[299] = 0;
    AddEvent(t);            // the result goes to the event list only
    ShowDriverStatus();     // the quality block shows what the driver runs with
    return true;
}

// ---------------------------------------------------------------------------
// Apply

// The microphone's volume and mute just before "Apply" restarts the device: Windows may bring back older values
// afterwards (a change made shortly before is not stored yet), so they are held once the endpoints are back.
static struct { bool ok; float db; bool mute; } g_levelBeforeApply;

static void OnApply()
{
    Settings s = SettingsFromControls();
    {
        int mic = FindCableDevice(false);
        float mn = 0, mx = 0;
        g_levelBeforeApply.ok = mic >= 0 && GetEndpointVolumeDb(g_devs[mic].id, &g_levelBeforeApply.db, &mn, &mx) &&
                                GetEndpointMute(g_devs[mic].id, &g_levelBeforeApply.mute);
    }
    // The cable devices disappear during the restart: release them first.
    StopTest();
    StopMusic();
    StopMeters();
    SetText(IDC_SETTINGS_STATUS, TR(L"Применение настроек, устройство перезапускается…"));
    UpdateWindow(g_wnd);

    MarkDriverLog();
    AppLog(L"apply requested: rate=%lu channels=%lu bits=%lu latency=%lu (elevated=%d)",
           s.rate, s.channels, s.bits, s.latency, (int)g_elevated);
    AppLog(L"apply requested: microphone channels %lu (0 = as the speaker)", s.micChannels);
    int rc = g_elevated ? ApplySettings(s) : ApplyElevated(g_wnd, s);
    AppLog(L"apply finished: code %d", rc);
    const wchar_t* msg = nullptr;
    switch (rc)
    {
    case 0:  msg = nullptr; break;
    case -1: msg = TR(L"Нужны права администратора: запрос был отклонён."); break;
    case 2:  msg = TR(L"Драйвер Speak2Mic не установлен."); break;
    case 3:  msg = TR(L"Настройки сохранены, но устройство Speak2Mic не найдено: применятся после его установки."); break;
    case 5:  msg = TR(L"Настройки сохранены. Windows не смогла перезапустить устройство на ходу — перезагрузите компьютер."); break;
    default: msg = TR(L"Настройки сохранены, но перезапустить устройство не удалось: перезагрузите компьютер."); break;
    }

    g_driverInstalled = ReadSettings(&g_settings);
    ShowDriverStatus();
    if (msg) AddEvent(msg);     // shown in the event list; the quality block keeps the driver status

    // Give Windows a moment to re-create the endpoints, then pick them up again and set their
    // default format (Windows keeps the old one otherwise).
    SetTimer(g_wnd, TIMER_REFRESH, 2500, nullptr);
    if (rc == 0 || rc == 3)
    {
        g_formatTarget = s;
        g_formatTries = 8;
        g_formatOnlyIfWrong = false;
    }
}

// ---------------------------------------------------------------------------
// Settings file (export / import). Everything except the interface language:
//   [Speak2Mic] SampleRate, Channels, BitsPerSample, LatencyMs, SpeakerName, MicName, MicVolumePercent, MicMute
// UTF-16 INI (WritePrivateProfileString keeps Unicode when the file starts with a UTF-16 BOM).

static const wchar_t kIniSection[] = L"Speak2Mic";

static bool AskFileName(bool save, wchar_t* path)
{
    // Filter "<description>\0*.ini\0\0" (the description is translated).
    wchar_t filter[160];
    _snwprintf(filter, 150, L"%ls", TR(L"Файлы настроек Speak2Mic (*.ini)"));
    filter[149] = 0;
    size_t n = wcslen(filter) + 1;
    wcscpy(filter + n, L"*.ini");
    filter[n + 6] = 0;
    OPENFILENAMEW ofn = {};
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = g_wnd;
    ofn.lpstrFilter = filter;
    ofn.lpstrFile = path;
    ofn.nMaxFile = MAX_PATH;
    ofn.lpstrDefExt = L"ini";
    ofn.Flags = OFN_NOCHANGEDIR | (save ? OFN_OVERWRITEPROMPT : (OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST));
    return save ? GetSaveFileNameW(&ofn) != FALSE : GetOpenFileNameW(&ofn) != FALSE;
}

static void IoStatus(const wchar_t* fmt, const wchar_t* path, DWORD code)
{
    wchar_t t[MAX_PATH + 200];
    if (path) _snwprintf(t, MAX_PATH + 200, fmt, path);
    else _snwprintf(t, MAX_PATH + 200, fmt, code);
    t[MAX_PATH + 199] = 0;
    AddEvent( t);
}

static void OnExport()
{
    wchar_t path[MAX_PATH] = L"Speak2Mic.ini";
    if (!AskFileName(true, path)) return;

    HANDLE f = CreateFileW(path, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (f == INVALID_HANDLE_VALUE)
    {
        IoStatus(TR(L"Не удалось сохранить настройки (код %lu)."), nullptr, GetLastError());
        return;
    }
    const WORD bom = 0xFEFF;
    DWORD written = 0;
    WriteFile(f, &bom, sizeof(bom), &written, nullptr);
    CloseHandle(f);

    wchar_t v[256];
    auto put = [&](const wchar_t* key, const wchar_t* value) { WritePrivateProfileStringW(kIniSection, key, value, path); };
    auto putNum = [&](const wchar_t* key, long value) { _snwprintf(v, 256, L"%ld", value); put(key, v); };
    put(L"Version", L"" S2M_VER_STR);
    // The applied driver settings (not unapplied edits in the panel).
    putNum(L"SampleRate", (long)g_settings.rate);
    putNum(L"Channels", (long)g_settings.channels);
    putNum(L"MicChannels", (long)g_settings.micChannels);
    putNum(L"BitsPerSample", (long)g_settings.bits);
    putNum(L"LatencyMs", (long)g_settings.latency);
    for (int side = 0; side < 2; side++)
    {
        int i = FindCableDevice(side == 0);
        put(side == 0 ? L"SpeakerName" : L"MicName", i >= 0 && g_devs[i].desc[0] ? g_devs[i].desc : kDefaultName[side]);
    }
    int mic = FindCableDevice(false);
    float db = 0, mn = 0, mx = 0;
    bool mute = false;
    if (mic >= 0 && GetEndpointVolumeDb(g_devs[mic].id, &db, &mn, &mx)) putNum(L"MicVolumePercent", DbToPercent(db));
    if (mic >= 0 && GetEndpointMute(g_devs[mic].id, &mute)) putNum(L"MicMute", mute ? 1 : 0);
    bool ok = WritePrivateProfileStringW(nullptr, nullptr, nullptr, path) != FALSE;     // flush
    AppLog(L"settings exported to %ls", path);
    if (ok || GetFileAttributesW(path) != INVALID_FILE_ATTRIBUTES)
        IoStatus(TR(L"Настройки сохранены в %ls"), path, 0);
    else
        IoStatus(TR(L"Не удалось сохранить настройки (код %lu)."), nullptr, GetLastError());
}

static bool InList(DWORD v, const DWORD* list, int n)
{
    for (int i = 0; i < n; i++)
        if (list[i] == v) return true;
    return false;
}

static void OnImport()
{
    wchar_t path[MAX_PATH] = L"";
    if (!AskFileName(false, path)) return;

    const DWORD none = 0xFFFFFFFF;
    auto num = [&](const wchar_t* key) { return (DWORD)GetPrivateProfileIntW(kIniSection, key, (INT)none, path); };
    wchar_t names[2][256];
    GetPrivateProfileStringW(kIniSection, L"SpeakerName", L"", names[0], 256, path);
    GetPrivateProfileStringW(kIniSection, L"MicName", L"", names[1], 256, path);
    DWORD micChannels = num(L"MicChannels");
    DWORD rate = num(L"SampleRate"), channels = num(L"Channels"), bits = num(L"BitsPerSample"),
          latency = num(L"LatencyMs"), volume = num(L"MicVolumePercent"), mute = num(L"MicMute");
    if (rate == none && channels == none && bits == none && latency == none && micChannels == none &&
        !names[0][0] && !names[1][0] &&
        volume == none && mute == none)
    {
        IoStatus(TR(L"Файл не похож на настройки Speak2Mic."), nullptr, 0);
        return;
    }
    AppLog(L"settings import from %ls: rate=%ld channels=%ld bits=%ld latency=%ld volume=%ld mute=%ld", path,
           (long)rate, (long)channels, (long)bits, (long)latency, (long)volume, (long)mute);

    // Names and microphone volume/mute: applied right away (values that make no sense are skipped).
    for (int side = 0; side < 2; side++)
    {
        wchar_t* n = names[side];
        for (wchar_t* c = n; *c; c++)
            if (*c == L'"') *c = L'\'';
        if (!n[0] || wcslen(n) > 60) continue;
        int i = FindCableDevice(side == 0);
        if (i >= 0 && wcscmp(g_devs[i].desc, n) != 0 && SUCCEEDED(RenameSide(side, n, true))) SaveName(side, n);
        g_shownName[side][0] = 0;
    }
    int mic = FindCableDevice(false);
    if (mic >= 0 && volume != none && volume <= 1000)
    {
        float db = volume > 0 ? 20.0f * log10f(volume / 100.0f) : -96.0f;
        SetEndpointVolumeDb(g_devs[mic].id, db);
        SaveMicVolume(db);
    }
    if (mic >= 0 && (mute == 0 || mute == 1)) SetEndpointMute(g_devs[mic].id, mute == 1);
    g_micVolShown = -2;
    g_micMuteShown = -2;

    // Signal quality: shown in the controls and applied like "Apply" when it differs from the driver.
    Settings s = g_settings;
    if (InList(rate, kRates, (int)(sizeof(kRates) / sizeof(kRates[0])))) s.rate = rate;
    if (InList(channels, kChannels, (int)(sizeof(kChannels) / sizeof(kChannels[0])))) s.channels = channels;
    if (micChannels == 0 || InList(micChannels, kChannels, (int)(sizeof(kChannels) / sizeof(kChannels[0]))))
        s.micChannels = micChannels;
    if (InList(bits, kBits, (int)(sizeof(kBits) / sizeof(kBits[0])))) s.bits = bits;
    if (latency != none && latency >= 10 && latency <= 500) s.latency = latency;
    ShowSettings(s);
    IoStatus(TR(L"Настройки загружены из %ls"), path, 0);
    bool qualityChanges = g_driverInstalled && (s.rate != g_settings.rate || s.channels != g_settings.channels ||
                                                s.bits != g_settings.bits || s.latency != g_settings.latency ||
                                                s.micChannels != g_settings.micChannels);
    if (qualityChanges)
        OnApply();
    else
        RefreshDevices();
}

// ---------------------------------------------------------------------------
// Windows volume mixer (sndvol.exe: per-program volumes; it opens on the default playback device, and its
// device list switches to "Speak2Mic Speaker" when that is not the default).

static void OnMixer()
{
    wchar_t exe[MAX_PATH];
    GetSystemDirectoryW(exe, MAX_PATH);
    wcsncat(exe, L"\\SndVol.exe", MAX_PATH - wcslen(exe) - 1);
    HINSTANCE r = ShellExecuteW(g_wnd, L"open", exe, nullptr, nullptr, SW_SHOWNORMAL);
    AppLog(L"volume mixer: %ls (%ld)", exe, (long)(INT_PTR)r);
}

// ---------------------------------------------------------------------------
// Reset everything

// Signal quality -> preset "Standard" (device restart like "Apply" if needed), device names -> defaults.
// The interface language is kept.
static void OnResetAll()
{
    if (MessageBoxW(g_wnd, TR(L"Сбросить все настройки Speak2Mic к стандартным?\n\nКачество сигнала — пресет «Стандарт», имена устройств — по умолчанию."),
                    L"Speak2Mic", MB_YESNO | MB_ICONQUESTION) != IDYES)
        return;
    AppLog(L"reset all settings requested");

    // Names first: the device restart below would otherwise make the panel wait for the endpoints.
    for (int side = 0; side < 2; side++)
    {
        SaveName(side, kDefaultName[side]);
        int i = FindCableDevice(side == 0);
        if (i >= 0 && wcscmp(g_devs[i].desc, kDefaultName[side]) != 0) RenameSide(side, kDefaultName[side], true);
        g_updatingControls = true;
        SetWindowTextW(Ctl(side == 0 ? IDC_SPKNAME : IDC_MICNAME), kDefaultName[side]);
        g_updatingControls = false;
        g_shownName[side][0] = 0;
    }

    Settings standard;
    standard.rate = 48000;
    standard.channels = 2;
    standard.bits = 16;
    standard.latency = 30;
    standard.micChannels = 1;
    ShowSettings(standard);
    int mic = FindCableDevice(false);
    if (mic >= 0)
    {
        SetEndpointVolumeDb(g_devs[mic].id, 0.0f);     // 100 % = unity gain (Windows' own "100 %" is +9.56 dB)
        SaveMicVolume(0.0f);
        SetEndpointMute(g_devs[mic].id, false);
    }
    g_micVolShown = -2;
    g_micMuteShown = -2;

    bool qualityChanges = g_driverInstalled &&
        (g_settings.rate != standard.rate || g_settings.channels != standard.channels ||
         g_settings.bits != standard.bits || g_settings.latency != standard.latency ||
         g_settings.micChannels != standard.micChannels);

    AddEvent( TR(L"Все настройки сброшены к стандартным."));
    if (qualityChanges)
        OnApply();
    else
        RefreshDevices();
}

// ---------------------------------------------------------------------------
// Window procedure

// ---------------------------------------------------------------------------
// Tray: "Minimize" hides the window and shows an icon in the notification area (everything keeps running: volume
// protection, music). Click: the window again; right click: Open / Exit. "/t" starts the panel there.

#define WM_APP_TRAY (WM_APP + 24)
enum { IDM_TRAY_OPEN = 40001, IDM_TRAY_EXIT };
static bool g_inTray;
static UINT g_msgTaskbarCreated, g_msgShowPanel;    // Explorer restarted / a second start asks to show the panel

static void TrayIcon(DWORD op)
{
    NOTIFYICONDATAW nid = {};
    nid.cbSize = sizeof(nid);
    nid.hWnd = g_wnd;
    nid.uID = 1;
    if (op != NIM_DELETE)
    {
        nid.uFlags = NIF_MESSAGE | NIF_ICON | NIF_TIP;
        nid.uCallbackMessage = WM_APP_TRAY;
        nid.hIcon = (HICON)LoadImageW(g_inst, MAKEINTRESOURCEW(1), IMAGE_ICON, GetSystemMetrics(SM_CXSMICON),
                                      GetSystemMetrics(SM_CYSMICON), 0);
        _snwprintf(nid.szTip, 128, L"%ls", TR(L"Speak2Mic — панель управления"));
        nid.szTip[127] = 0;
    }
    Shell_NotifyIconW(op, &nid);
    if (nid.hIcon) DestroyIcon(nid.hIcon);
}

static void ToTray()
{
    if (!g_inTray) TrayIcon(NIM_ADD);
    g_inTray = true;
    ShowWindow(g_wnd, SW_HIDE);
    AppLog(L"panel minimized to the tray");
}

static void FromTray()
{
    ShowWindow(g_wnd, SW_SHOW);
    if (IsIconic(g_wnd)) ShowWindow(g_wnd, SW_RESTORE);
    SetForegroundWindow(g_wnd);
    if (g_inTray) TrayIcon(NIM_DELETE);
    g_inTray = false;
}

static void TrayMenu()
{
    HMENU menu = CreatePopupMenu();
    AppendMenuW(menu, MF_STRING, IDM_TRAY_OPEN, TR(L"Открыть панель управления"));
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, IDM_TRAY_EXIT, TR(L"Выход"));
    SetMenuDefaultItem(menu, IDM_TRAY_OPEN, FALSE);
    POINT pt;
    GetCursorPos(&pt);
    SetForegroundWindow(g_wnd);              // or the menu does not close when clicking elsewhere
    TrackPopupMenu(menu, TPM_RIGHTBUTTON, pt.x, pt.y, 0, g_wnd, nullptr);
    PostMessageW(g_wnd, WM_NULL, 0, 0);
    DestroyMenu(menu);
}

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    if (msg && msg == g_msgTaskbarCreated)
    {
        if (g_inTray) TrayIcon(NIM_ADD);     // Explorer restarted: the icon is gone
        return 0;
    }
    if (msg && msg == g_msgShowPanel)
    {
        FromTray();
        return 0;
    }
    switch (msg)
    {
    case WM_CREATE:
        g_wnd = hwnd;
        g_dpi = GetDpiForWindow(hwnd);
        CreateControls();
        LoadEvents();
        FitEventList(nullptr);
        {
            wchar_t started[160];
            _snwprintf(started, 160, TR(L"Панель управления Speak2Mic запущена, версия %ls"), L"" S2M_VER_STR);
            started[159] = 0;
            AddEvent(started);
        }
        ApplyFonts();
        Layout();
        MarkDriverLog();
        wcscpy(g_driverLogMark + 11, L"00:00:00.000");         // from midnight today
        g_driverInstalled = ReadSettings(&g_settings);
        AppLog(L"driver settings: %ls rate=%lu channels=%lu bits=%lu latency=%lu",
               g_driverInstalled ? L"installed" : L"NOT installed", g_settings.rate,
               g_settings.channels, g_settings.bits, g_settings.latency);
        ShowSettings(g_settings);
        ShowDriverStatus();
        RefreshDevices();
        RestoreSavedNames();
        SetTimer(hwnd, TIMER_METERS, 33, nullptr);
        SetTimer(hwnd, TIMER_MP3, 2000, nullptr);
        UpdatePlayButton();
        SendMessageW(Ctl(IDC_AUTOSTART), BM_SETCHECK, S2mAutostartEnabled() ? BST_CHECKED : BST_UNCHECKED, 0);
        EnsureMicWatch();
        if (g_driverInstalled)
        {
            // Windows keeps an endpoint's default format across driver restarts and reinstalls; if the
            // driver settings changed meanwhile, that format no longer opens. Fix such endpoints now.
            g_formatTarget = g_settings;
            g_formatTries = 1;
            g_formatOnlyIfWrong = true;
            SetTimer(hwnd, TIMER_FORMAT, 300, nullptr);
        }
        return 0;

    case WM_DPICHANGED:
    {
        g_dpi = HIWORD(wp);
        RECT* r = (RECT*)lp;
        SetWindowPos(hwnd, nullptr, r->left, r->top, r->right - r->left, r->bottom - r->top, SWP_NOZORDER | SWP_NOACTIVATE);
        ApplyFonts();
        ApplyToolIcons();
        Layout();
        return 0;
    }

    case WM_TIMER:
        if (wp == TIMER_MP3)
        {
            UpdatePlayButton();             // .mp3 files added to / removed from the folder
            EnsureMicWatch();               // the microphone endpoint may have been recreated
            return 0;
        }
        if (wp == TIMER_METERS)
        {
            UpdateMeterUi(g_meterIn, g_inFound, IDC_IN_METER, IDC_IN_DB, IDC_IN_FORMAT);
            UpdateMeterUi(g_meterOut, g_outFound, IDC_OUT_METER, IDC_OUT_DB, IDC_OUT_FORMAT);
            // No "refresh" button: while a Speak2Mic device is missing (driver installed or restarted after
            // the panel started), look for it every ~3 s and connect the meters once it is there.
            static int tick;
            if (++tick % 15 == 0) SyncMicVolume();      // ~0.5 s: follow changes made in Sound settings
            // Reconnect a meter whose capture ended: Windows invalidates the streams when the device format
            // changes (Sound settings, another program) or the driver restarts. ~2 s between tries.
            // After 5 failed tries in a row every ~10 s, so a really broken device does not flood panel.log.
            static int reconnects, wait;
            bool ended = (g_inFound && g_meterIn.Ended()) || (g_outFound && g_meterOut.Ended());
            if (!ended) reconnects = 0;
            if (ended && wait > 0) wait--;
            if (ended && wait <= 0 && g_formatTries <= 0)
            {
                wait = reconnects++ < 5 ? 60 : 300;
                AppLog(L"meters: capture ended (%ls / %ls), reconnecting", g_meterIn.Ended() ? L"speaker" : L"ok",
                       g_meterOut.Ended() ? L"mic" : L"ok");
                RefreshDevices();
            }
            else if (tick % 90 == 0 && (!g_inFound || !g_outFound) && g_formatTries <= 0 && SpeakDevicesAppeared())
                RefreshDevices();
        }
        else if (wp == TIMER_REFRESH)
        {
            KillTimer(hwnd, TIMER_REFRESH);
            RefreshDevices(g_formatTries <= 0);
            if (g_formatTries > 0)
            {
                SetText(IDC_SETTINGS_STATUS, TR(L"Установка формата по умолчанию для устройств Speak2Mic…"));
                SetTimer(hwnd, TIMER_FORMAT, 100, nullptr);
            }
        }
        else if (wp == TIMER_FORMAT)
        {
            KillTimer(hwnd, TIMER_FORMAT);
            StopMeters();                       // g_devs is refreshed by RefreshDevices below
            g_devCount = ListAudioDevices(g_devs, 128);
            if (ApplyEndpointFormats())
            {
                g_formatTries = 0;
                int mic = FindCableDevice(false);
                if (g_levelBeforeApply.ok && mic >= 0)
                {
                    EndpointHold hold = { g_devs[mic].id, false, 0, 0, 0, true, g_levelBeforeApply.db, g_levelBeforeApply.mute };
                    HoldEndpointSettings(&hold, 1, 1500);
                }
                g_levelBeforeApply.ok = false;
                StartMeters();
            }
            else
            {
                SetTimer(hwnd, TIMER_FORMAT, 1500, nullptr);
            }
        }
        return 0;

    case WM_APP_FOREIGN_VOLUME:
        OnForeignMicVolume((LONG)(LONG_PTR)wp / 100.0f);
        return 0;

    case WM_APP_PLAY_TRACK:
    {
        wchar_t* name = (wchar_t*)lp;
        wchar_t t[400];
        _snwprintf(t, 400, TR(L"Музыка: следующий трек (%ls)."), name ? name : L"?");
        t[399] = 0;
        AddEvent(t);
        free(name);
        return 0;
    }

    case WM_APP_PLAY_DONE:
        OnPlayDone((HRESULT)wp);
        return 0;

    case WM_APP_TEST_DONE:
        OnTestDone((HRESULT)wp);
        return 0;

    case WM_SYSCOMMAND:
        if ((wp & 0xFFF0) == SC_MINIMIZE)
        {
            ToTray();
            return 0;
        }
        break;

    case WM_APP_TRAY:
        if (lp == WM_LBUTTONUP || lp == WM_LBUTTONDBLCLK) FromTray();
        else if (lp == WM_RBUTTONUP || lp == WM_CONTEXTMENU) TrayMenu();
        return 0;

    case WM_NOTIFY:
    {
        NMHDR* h = (NMHDR*)lp;
        if (h->code == TTN_GETDISPINFOW && h->hwndFrom == g_eventTip && h->idFrom == (UINT_PTR)Ctl(IDC_IO_STATUS))
        {
            EventTipText((NMTTDISPINFOW*)lp);
            return 0;
        }
        break;
    }

    case WM_HSCROLL:
        if ((HWND)lp == Ctl(IDC_MICVOL)) OnMicVolumeSlider(LOWORD(wp));
        return 0;

    case WM_COMMAND:
    {
        int id = LOWORD(wp), code = HIWORD(wp);
        if (id == IDM_TRAY_OPEN) { FromTray(); return 0; }
        if (id == IDM_TRAY_EXIT) { PostMessageW(hwnd, WM_CLOSE, 0, 0); return 0; }
        if (code == CBN_SELCHANGE && !g_updatingControls)
        {
            if (id == IDC_LANG)
            {
                if (LangApplyCombo(Ctl(IDC_LANG))) PostMessageW(hwnd, WM_CLOSE, 0, 0);   // a new copy starts
            }
            else if (id == IDC_PRESET)
            {
                int p = ComboSel(IDC_PRESET);
                if (p > 0)
                {
                    g_updatingControls = true;
                    ComboSelectData(IDC_RATE, kPresets[p].rate);
                    ComboSelectData(IDC_BITS, kPresets[p].bits);
                    ComboSelectData(IDC_CHANNELS, kPresets[p].channels);
                    ComboSelectData(IDC_MICCHANNELS, 1);       // every preset: mono microphone
                    g_updatingControls = false;
                }
            }
            else if (id == IDC_RATE || id == IDC_BITS || id == IDC_CHANNELS)
            {
                SyncPreset();
            }
            if (id == IDC_PRESET || id == IDC_RATE || id == IDC_BITS || id == IDC_CHANNELS || id == IDC_MICCHANNELS)
                UpdateApplyButton();
        }
        else if (code == EN_CHANGE && id == IDC_LATENCY && !g_updatingControls)
        {
            UpdateApplyButton();    // typed or changed with the up/down arrows
        }
        else if (code == EN_CHANGE && (id == IDC_SPKNAME || id == IDC_MICNAME) && !g_updatingControls)
        {
            UpdateRenameButton();
        }
        else if (code == BN_CLICKED)
        {
            if (id == IDC_APPLY) OnApply();
            else if (id == IDC_RENAME) OnRename();
            else if (id == IDC_RESET_ALL) OnResetAll();
            else if (id == IDC_MIXER) OnMixer();
            else if (id == IDC_CLEARLOG) ClearEvents();
            else if (id == IDC_MICMUTE) OnMicMute();
            else if (id == IDC_AUTOSTART)
            {
                bool on = SendMessageW(Ctl(IDC_AUTOSTART), BM_GETCHECK, 0, 0) == BST_CHECKED;
                wchar_t exe[MAX_PATH];
                GetModuleFileNameW(nullptr, exe, MAX_PATH);
                if (S2mSetAutostart(on, exe, true))
                    AddEvent(on ? TR(L"Автозагрузка панели управления включена.") : TR(L"Автозагрузка панели управления выключена."));
                SendMessageW(Ctl(IDC_AUTOSTART), BM_SETCHECK, S2mAutostartEnabled() ? BST_CHECKED : BST_UNCHECKED, 0);
            }
            else if (id == IDC_EXPORT) OnExport();
            else if (id == IDC_TEST) OnTest();
            else if (id == IDC_PLAY) OnPlay();
            else if (id == IDC_IMPORT) OnImport();
        }
        return 0;
    }

    case WM_CLOSE:
        if (g_inTray) TrayIcon(NIM_DELETE);
        g_inTray = false;
        UnwatchEndpointVolume(g_micWatch);
        g_micWatch = nullptr;
        StopTest();
        StopMusic();
        AppLog(L"panel closed");
        KillTimer(hwnd, TIMER_METERS);
        StopMeters();
        DestroyWindow(hwnd);
        return 0;

    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

// ---------------------------------------------------------------------------

// Named mutex held for the lifetime of the panel (released by Windows when the process exits).
static HANDLE g_instanceMutex;

static bool g_startInTray;      // "/t": start in the tray (and a second start with /t does not show the running one)

static bool AcquireSingleInstance(bool waitForPrevious)
{
    g_instanceMutex = CreateMutexW(nullptr, TRUE, L"Local\\Speak2Mic.ControlPanel");
    DWORD err = GetLastError();
    if (g_instanceMutex && err != ERROR_ALREADY_EXISTS) return true;
    // ERROR_ACCESS_DENIED: the running panel is elevated and this one is not; it exists all the same.
    if (g_instanceMutex && waitForPrevious)
    {
        DWORD w = WaitForSingleObject(g_instanceMutex, 10000);
        if (w == WAIT_OBJECT_0 || w == WAIT_ABANDONED) return true;
    }
    HWND other = FindWindowW(L"S2mPanel", nullptr);
    if (other && !g_startInTray)
    {
        // also when it sits in the tray (a hidden window): it shows itself
        AllowSetForegroundWindow(ASFW_ANY);
        PostMessageW(other, g_msgShowPanel, 0, 0);
    }
    return false;
}

int WINAPI wWinMain(HINSTANCE inst, HINSTANCE, PWSTR, int show)
{
    g_inst = inst;
    AppLogOpen(L"panel");
    AppLog(L"Speak2Mic control panel " S2M_VER_STR);

    // Elevated helper mode: s2mpanel --apply <rate> <channels> <bits> <latency> <mic channels>
    int argc = 0;
    wchar_t** argv = CommandLineToArgvW(GetCommandLineW(), &argc);
    // Helper mode for the installer: s2mpanel --set-formats. After an install / update Windows recreates the
    // endpoints with the INF default format (speaker stereo, microphone mono); this puts the saved settings
    // (rate, bits, channels of each side) on them. Waits up to 15 s for the endpoints. Exit code 0 = done.
    if (argv && argc == 2 && _wcsicmp(argv[1], L"--set-formats") == 0)
    {
        LocalFree(argv);
        CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
        Settings s;
        ReadSettings(&s);
        WORD bits = (WORD)(s.bits ? s.bits : 24);
        static AudioDevice list[128];
        int done = 0;
        for (int tries = 0; tries < 30 && done < 2; tries++)
        {
            if (tries) Sleep(500);
            int n = ListAudioDevices(list, 128);
            done = 0;
            for (int side = 0; side < 2; side++)
            {
                int i = FindInList(list, n, side == 0);
                if (i < 0) break;
                DWORD ch = side == 0 || !s.micChannels ? s.channels : s.micChannels;
                wchar_t err[160];
                bool ok = SetEndpointFormat(list[i].id, s.rate, bits, (WORD)ch, err, 160);
                if (!ok && bits > 16) ok = SetEndpointFormat(list[i].id, s.rate, 16, (WORD)ch, err, 160);
                AppLog(L"set-formats \"%ls\": %lu Hz %u bit %lu ch -> %ls (%ls)", list[i].name, s.rate, bits, ch,
                       ok ? L"ok" : L"FAILED", err);
                done++;
            }
        }
        CoUninitialize();
        return done == 2 ? 0 : 1;
    }

    // Elevated helper mode: s2mpanel --cleanup  (removes stale Speak2Mic endpoints; exit code = count)
    if (argv && argc == 2 && _wcsicmp(argv[1], L"--cleanup") == 0)
    {
        LocalFree(argv);
        int n = S2mStaleEndpoints(true);
        int renamed = S2mSyncEndpointNames(true);
        AppLog(L"cleanup (elevated helper): %d stale endpoint(s) removed, %d Device Manager name(s) updated", n, renamed);
        return n + renamed;
    }

    // Elevated helper mode: s2mpanel --rename speaker|mic "<name>"  (exit code = HRESULT)
    if (argv && argc == 4 && _wcsicmp(argv[1], L"--rename") == 0)
    {
        bool input = _wcsicmp(argv[2], L"speaker") == 0;
        HRESULT hr = E_NOTFOUND;
        CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
        static AudioDevice list[128];
        int n = ListAudioDevices(list, 128);
        int i = FindInList(list, n, input);
        if (i >= 0) hr = SetEndpointName(list[i].id, argv[3]);
        AppLog(L"rename (elevated helper) %ls -> \"%ls\": 0x%08lX", argv[2], argv[3], (unsigned long)hr);
        CoUninitialize();
        LocalFree(argv);
        return (int)hr;
    }
    if (argv && argc == 7 && _wcsicmp(argv[1], L"--apply") == 0)
    {
        Settings s;
        s.rate = (DWORD)_wtoi(argv[2]);
        s.channels = (DWORD)_wtoi(argv[3]);
        s.bits = (DWORD)_wtoi(argv[4]);
        s.latency = (DWORD)_wtoi(argv[5]);
        s.micChannels = (DWORD)_wtoi(argv[6]);
        LocalFree(argv);
        return ApplySettings(s);
    }
    // Only one control panel: a second start brings the running one to the front instead.
    // After a language change the new copy is started while the old one is closing (--restarted):
    // it waits for the old one to exit.
    bool restarted = false, tray = false;
    for (int i = 1; argv && i < argc; i++)
    {
        if (_wcsicmp(argv[i], L"--restarted") == 0) restarted = true;
        if (_wcsicmp(argv[i], L"/t") == 0 || _wcsicmp(argv[i], L"-t") == 0 || _wcsicmp(argv[i], L"--tray") == 0) tray = true;
    }
    g_msgTaskbarCreated = RegisterWindowMessageW(L"TaskbarCreated");
    g_msgShowPanel = RegisterWindowMessageW(L"Speak2Mic.ShowPanel");
    g_startInTray = tray;
    if (argv) LocalFree(argv);

    // Nothing here works without the driver, and the driver loads only in test signing mode (Secure Boot off).
    S2mNotReady notReady = S2mCheckReady();
    if (notReady != S2mReadyOk && g_startInTray)
    {
        AppLog(L"started in the tray (autostart) but not ready: exiting without a message");
        return 1;                            // no message box at every logon
    }
    if (notReady != S2mReadyOk)
    {
        wchar_t setup[MAX_PATH], text[1200];
        GetModuleFileNameW(nullptr, setup, MAX_PATH);
        wchar_t* slash = wcsrchr(setup, L'\\');
        wcscpy(slash ? slash + 1 : setup, L"Speak2Mic-Setup.exe");
        bool haveSetup = GetFileAttributesW(setup) != INVALID_FILE_ATTRIBUTES;
        _snwprintf(text, 1200, haveSetup ? L"%ls\n\n%ls" : L"%ls", S2mNotReadyText(notReady), TR(L"Открыть установщик Speak2Mic сейчас?"));
        text[1199] = 0;
        if (MessageBoxW(nullptr, text, L"Speak2Mic", (haveSetup ? MB_YESNO : MB_OK) | MB_ICONERROR) == IDYES)
            ShellExecuteW(nullptr, L"open", setup, nullptr, nullptr, SW_SHOWNORMAL);
        return 1;
    }
    if (!AcquireSingleInstance(restarted))
    {
        AppLog(L"another control panel is running: activating it");
        return 0;
    }

    g_elevated = IsElevated();
    CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);

    INITCOMMONCONTROLSEX icc = { sizeof(icc), ICC_STANDARD_CLASSES | ICC_UPDOWN_CLASS | ICC_BAR_CLASSES };
    InitCommonControlsEx(&icc);

    WNDCLASSEXW mc = { sizeof(mc) };
    mc.lpfnWndProc = MeterProc;
    mc.hInstance = inst;
    mc.hCursor = LoadCursorW(nullptr, IDC_ARROW);
    mc.lpszClassName = L"S2mMeter";
    RegisterClassExW(&mc);

    WNDCLASSEXW wc = { sizeof(wc) };
    wc.lpfnWndProc = WndProc;
    wc.hInstance = inst;
    wc.hCursor = LoadCursorW(nullptr, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    wc.hIcon = LoadIconW(inst, MAKEINTRESOURCEW(1));
    wc.lpszClassName = L"S2mPanel";
    RegisterClassExW(&wc);

    // Size the window for the monitor DPI: 600x666 client area at 96 DPI.
    UINT dpi = GetDpiForSystem();
    RECT r = { 0, 0, MulDiv(600, (int)dpi, 96), MulDiv(666, (int)dpi, 96) };
    DWORD style = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX;
    AdjustWindowRectExForDpi(&r, style, FALSE, WS_EX_CONTROLPARENT, dpi);
    wchar_t title[160];
    _snwprintf(title, 160, L"%ls %ls", TR(L"Speak2Mic — панель управления"), L"" S2M_VER_STR);
    title[159] = 0;
    HWND hwnd = CreateWindowExW(WS_EX_CONTROLPARENT, L"S2mPanel", title, style,
                                CW_USEDEFAULT, CW_USEDEFAULT, r.right - r.left, r.bottom - r.top,
                                nullptr, nullptr, inst, nullptr);
    if (!hwnd) return 1;
    if (g_startInTray) ToTray();
    else ShowWindow(hwnd, show);

    MSG m;
    while (GetMessageW(&m, nullptr, 0, 0) > 0)
    {
        if (!IsDialogMessageW(hwnd, &m))
        {
            TranslateMessage(&m);
            DispatchMessageW(&m);
        }
    }
    CoUninitialize();
    return 0;
}
