// Speak2Mic-Setup.exe - graphical installer for the Speak2Mic driver.
//
// Shows the system state (test signing, Secure Boot, driver), installs/removes the driver with
// a progress log, can turn on test signing, and starts the Speak2Mic panel after installation.
// Runs elevated (manifest: requireAdministrator). Expects Speak2Mic.inf/.sys/.cer next to it.
#include "../driver/version.h"   // S2M_VER_STR, generated by gen.py for every build
#include "lang.h"
#include "setupcore.h"
#include "autostart.h"
#include "diag.h"
#include "applog.h"
#include "audiosvc.h"
#include "devctl.h"
#include <commctrl.h>
#include <shellapi.h>
#include <stdio.h>
#include <stdlib.h>
#include <wchar.h>

enum
{
    IDC_TITLE = 100, IDC_SUBTITLE, IDC_GROUP, IDC_ST_TEST, IDC_ST_SECURE, IDC_ST_DRIVER,
    IDC_ENABLE_TEST, IDC_INSTALL, IDC_REMOVE, IDC_LOG, IDC_LAUNCH, IDC_CLOSE, IDC_DIAG, IDC_OPENLOG,
    IDC_LINK_DESKTOP, IDC_LINK_START, IDC_VERSION, IDC_LANG,
};
enum { ACT_INSTALL = 1, ACT_REMOVE, ACT_TESTSIGN, ACT_DIAG };
#define WM_APP_LOG  (WM_APP + 1)
#define WM_APP_DONE (WM_APP + 2)

static HINSTANCE g_inst;
static HWND      g_wnd;
static UINT      g_dpi = 96;
static HFONT     g_font, g_fontTitle;
static HICON     g_bigIcon;
static HBRUSH    g_whiteBrush;
static HANDLE    g_worker;
static int       g_action;
static bool      g_ok, g_reboot;
static DiagResult g_diag;
static bool      g_wantDesktop, g_wantStartMenu, g_selfDelete;
static bool      g_testOk, g_secureOk, g_driverOk, g_filesOk;
static bool      g_testNext;        // test signing as configured for the next start (may differ until a restart)
static bool      g_testTarget;      // what the "test mode" button is switching to
static bool      g_updateAvail;     // the installed driver is another version than this installer's ("Update")

static HWND Ctl(int id) { return GetDlgItem(g_wnd, id); }
static int S(int v) { return MulDiv(v, (int)g_dpi, 96); }

static void SiblingPath(const wchar_t* name, wchar_t* out)
{
    GetModuleFileNameW(nullptr, out, MAX_PATH);
    wchar_t* slash = wcsrchr(out, L'\\');
    wcscpy(slash ? slash + 1 : out, name);
}

// ---------------------------------------------------------------------------
// Log (thread-safe: worker posts heap copies of the lines)

static void AppendLog(const wchar_t* line)
{
    AppLog(L"%ls", line);
    HWND e = Ctl(IDC_LOG);
    int len = GetWindowTextLengthW(e);
    SendMessageW(e, EM_SETSEL, len, len);
    if (len) SendMessageW(e, EM_REPLACESEL, FALSE, (LPARAM)L"\r\n");
    SendMessageW(e, EM_REPLACESEL, FALSE, (LPARAM)line);
}

static void WorkerLog(void*, const wchar_t* line)
{
    PostMessageW(g_wnd, WM_APP_LOG, 0, (LPARAM)_wcsdup(line));
}

static void CloseRunningPanel();
static void ApplySavedFormats();

static DWORD WINAPI Worker(LPVOID)
{
    wchar_t inf[MAX_PATH], cer[MAX_PATH], pub[MAX_PATH];
    AudioServices audio;
    audio.count = 0;
    SiblingPath(L"Speak2Mic.inf", inf);
    SiblingPath(L"Speak2Mic.cer", cer);
    SiblingPath(L"Speak2Mic-Publisher.cer", pub);
    g_reboot = false;

    switch (g_action)
    {
    case ACT_INSTALL:
        CloseRunningPanel();
        WorkerLog(nullptr, TR(L"— Установка Speak2Mic —"));
        // Windows Audio is paused for the whole (re)installation: removing or restarting a device while
        // audiodg.exe streams to it leaves the endpoints unbuilt.
        WorkerLog(nullptr, TR(L"Остановка службы Windows Audio на время установки…"));
        AudioStopServices(false, &audio);
        if (SetupDeviceCount() > 0 && !SetupDevicePresent())
        {
            // Only a leftover registration: nothing to update in place.
            WorkerLog(nullptr, TR(L"Удаление предыдущей версии…"));
            SetupRemoveDriver(WorkerLog, nullptr, true);     // keep the settings
        }
        // An existing device is updated in place: removing it made Windows create a new pair of sound
        // endpoints on every update (the old ones stayed in Device Manager) and lose their names/volume.
        SetupResetDriverStatus();
        SetupTrustCertificate(cer, pub, WorkerLog, nullptr);
        g_ok = SetupInstallDriver(inf, &g_reboot, WorkerLog, nullptr);
        if (g_ok)
        {
            wchar_t dir[MAX_PATH];
            GetModuleFileNameW(nullptr, dir, MAX_PATH);
            wchar_t* slash = wcsrchr(dir, L'\\');
            if (slash) *slash = 0;
            SetupRemoveOldDriverPackages(WorkerLog, nullptr);
            if (SetupInstallFiles(dir, WorkerLog, nullptr) && (g_wantDesktop || g_wantStartMenu))
                {
                    // the panel starts with Windows (in the tray) unless the user switched that off in the panel
                    wchar_t panel[MAX_PATH];
                    if (S2mAutostartWanted() && SetupProgramDir(panel) && wcslen(panel) < MAX_PATH - 16)
                    {
                        wcscat(panel, L"\\Speak2Mic.exe");
                        S2mSetAutostart(true, panel, false);
                    }
                }
                SetupCreateShortcuts(g_wantDesktop, g_wantStartMenu, WorkerLog, nullptr);
        }
        AudioStartServices(&audio);
        WorkerLog(nullptr, TR(L"Служба Windows Audio запущена."));
        if (g_ok && !g_reboot)
        {
            // Do not report success blindly: wait for the device and its sound endpoints.
            WorkerLog(nullptr, TR(L"Проверка: ожидание запуска устройства и звуковых устройств…"));
            if (WaitForEndpoints(15000) != DiagOk)
            {
                // Endpoint builder did not pick the device up: restart the audio services completely.
                WorkerLog(nullptr, TR(L"Звуковые устройства не появились — перезапуск служб звука Windows…"));
                AudioServices all;
                AudioStopServices(true, &all);
                AudioStartServices(&all);
                if (WaitForEndpoints(15000) != DiagOk && S2mGetParam(L"ProposeFormat", 1) != 0)
                {
                    // Fallback for systems where answering format proposals on the filter keeps the
                    // Audio Endpoint Builder from creating the endpoints (seen with driver 1.0.269.743).
                    WorkerLog(nullptr, TR(L"Звуковые устройства всё ещё не появились — выключаю проверку форматов "
                                       L"в драйвере (ProposeFormat = 0) и перезапускаю устройство…"));
                    S2mSetParam(L"ProposeFormat", 0);
                    AudioServices svc;
                    AudioStopServices(false, &svc);
                    bool found = false, reboot = false;
                    S2mRestartDevice(&found, &reboot);
                    AudioStartServices(&svc);
                    WorkerLog(nullptr, WaitForEndpoints(15000) == DiagOk
                                           ? TR(L"С ProposeFormat = 0 звуковые устройства появились.")
                                           : TR(L"С ProposeFormat = 0 звуковые устройства тоже не появились."));
                }
            }
            // Endpoints left by earlier installations (Device Manager); restarts the audio services if any.
            if (SetupRemoveStaleEndpoints(WorkerLog, nullptr) > 0) WaitForEndpoints(15000);
            DiagSetMicUnityGain();      // a new microphone endpoint may start at +30 dB
            ApplySavedFormats();        // Windows recreated the endpoints with the INF default format
            S2mSyncEndpointNames(true);                      // names Device Manager shows for the present ones
            g_diag = RunDiagnostics(WorkerLog, nullptr);
        }
        break;
    case ACT_DIAG:
        WorkerLog(nullptr, TR(L"— Диагностика —"));
        g_diag = RunDiagnostics(WorkerLog, nullptr);
        g_ok = true;
        break;
    case ACT_REMOVE:
        CloseRunningPanel();
        WorkerLog(nullptr, TR(L"— Удаление Speak2Mic —"));
        AudioStopServices(false, &audio);
        g_ok = SetupRemoveDriver(WorkerLog, nullptr);
        SetupRemoveStaleEndpoints(WorkerLog, nullptr);
        AudioStartServices(&audio);
        SetupRemoveFiles(&g_selfDelete, WorkerLog, nullptr);
        break;
    case ACT_TESTSIGN:
        WorkerLog(nullptr, g_testTarget ? TR(L"— Включение тестового режима подписи —")
                                        : TR(L"— Выключение тестового режима подписи —"));
        g_ok = SetupSetTestSigning(g_testTarget, WorkerLog, nullptr);
        break;
    }
    PostMessageW(g_wnd, WM_APP_DONE, 0, 0);
    return 0;
}

// Closes a running control panel: it would keep the old Speak2Mic.exe in use (the copy fails) and, being
// single-instance, a panel started after the installation would only bring the old window to the front.
static void CloseRunningPanel()
{
    for (int tries = 0; tries < 3; tries++)
    {
        HWND panel = FindWindowW(L"S2mPanel", nullptr);
        if (!panel) return;
        DWORD pid = 0;
        GetWindowThreadProcessId(panel, &pid);
        HANDLE proc = OpenProcess(SYNCHRONIZE, FALSE, pid);
        PostMessageW(panel, WM_CLOSE, 0, 0);
        DWORD w = proc ? WaitForSingleObject(proc, 5000) : WAIT_FAILED;
        if (proc) CloseHandle(proc);
        AppLog(L"control panel (pid %lu) closed: %ls", pid, w == WAIT_OBJECT_0 ? L"yes" : L"not in time");
        if (!proc) Sleep(500);
    }
}

// Puts the saved signal quality (rate, bits, channels of the speaker and the microphone) on the endpoints
// through the installed control panel ("Speak2Mic.exe --set-formats"): after an update Windows creates them
// with the INF default format, which would look like the settings were reset.
static void ApplySavedFormats()
{
    wchar_t exe[MAX_PATH];
    if (!SetupProgramDir(exe)) return;
    wcsncat(exe, L"\\Speak2Mic.exe", MAX_PATH - wcslen(exe) - 1);
    if (GetFileAttributesW(exe) == INVALID_FILE_ATTRIBUTES) SiblingPath(L"Speak2Mic.exe", exe);
    wchar_t cmd[MAX_PATH + 32];
    _snwprintf(cmd, MAX_PATH + 32, L"\"%ls\" --set-formats", exe);
    cmd[MAX_PATH + 31] = 0;
    STARTUPINFOW si = { sizeof(si) };
    PROCESS_INFORMATION pi = {};
    if (!CreateProcessW(exe, cmd, nullptr, nullptr, FALSE, 0, nullptr, nullptr, &si, &pi))
    {
        AppLog(L"set-formats: cannot start %ls (%lu)", exe, GetLastError());
        return;
    }
    WaitForSingleObject(pi.hProcess, 30000);
    DWORD code = 1;
    GetExitCodeProcess(pi.hProcess, &code);
    AppLog(L"set-formats: exit code %lu", code);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
}

// ---------------------------------------------------------------------------
// State

static void RefreshState()
{
    wchar_t sys[MAX_PATH], inf[MAX_PATH], cer[MAX_PATH], pub[MAX_PATH], cat[MAX_PATH];
    SiblingPath(L"Speak2Mic.sys", sys);
    SiblingPath(L"Speak2Mic.inf", inf);
    SiblingPath(L"Speak2Mic.cer", cer);
    SiblingPath(L"Speak2Mic-Publisher.cer", pub);
    SiblingPath(L"Speak2Mic.cat", cat);
    g_filesOk = GetFileAttributesW(sys) != INVALID_FILE_ATTRIBUTES && GetFileAttributesW(inf) != INVALID_FILE_ATTRIBUTES &&
                GetFileAttributesW(cer) != INVALID_FILE_ATTRIBUTES && GetFileAttributesW(pub) != INVALID_FILE_ATTRIBUTES &&
                GetFileAttributesW(cat) != INVALID_FILE_ATTRIBUTES;

    bool secure = SetupSecureBootEnabled();
    g_testOk = SetupTestSigningEnabled();
    int configured = SetupTestSigningConfigured();
    g_testNext = configured < 0 ? g_testOk : configured != 0;
    g_secureOk = !secure;
    g_driverOk = SetupDeviceCount() > 0;

    SetWindowTextW(Ctl(IDC_ST_TEST), g_testOk
        ? (g_testNext ? TR(L"✔  Тестовый режим подписи включён")
                      : TR(L"✔  Тестовый режим подписи включён (до перезагрузки)"))
        : (g_testNext ? TR(L"✖  Тестовый режим подписи выключен (до перезагрузки)")
                      : TR(L"✖  Тестовый режим подписи выключен")));
    SetWindowTextW(Ctl(IDC_ST_SECURE), g_secureOk
        ? TR(L"✔  Secure Boot выключен")
        : TR(L"✖  Secure Boot включён"));
    // Installed = the version of the driver that last started (its log); the build of this installer
    // is shown under the title.
    wchar_t running[64] = L"", text[200];
    if (!g_driverOk)
        wcscpy(text, TR(L"•  Драйвер Speak2Mic не установлен"));
    else if (!DiagRunningDriverVersion(running, 64))
        wcscpy(text, TR(L"✔  Драйвер Speak2Mic установлен"));
    else if (wcscmp(running, L"" S2M_VER_STR) == 0)
        _snwprintf(text, 200, TR(L"✔  Драйвер Speak2Mic установлен, версия %ls (как в установщике)"), running);
    else
        _snwprintf(text, 200, TR(L"✔  Драйвер Speak2Mic установлен, версия %ls — в установщике %ls"), running, L"" S2M_VER_STR);
    text[199] = 0;
    SetWindowTextW(Ctl(IDC_ST_DRIVER), text);

    bool busy = g_worker != nullptr;
    // One button switches the mode for the next start: turning it on needs Secure Boot off.
    SetWindowTextW(Ctl(IDC_ENABLE_TEST), g_testNext ? TR(L"Выключить тестовый режим") : TR(L"Включить тестовый режим"));
    EnableWindow(Ctl(IDC_ENABLE_TEST), !busy && (g_testNext || g_secureOk));
    // The driver loads only in test signing mode (active now, not just configured) with Secure Boot off.
    EnableWindow(Ctl(IDC_INSTALL), !busy && g_filesOk && g_testOk && g_secureOk);
    EnableWindow(Ctl(IDC_REMOVE), !busy && g_driverOk);
    EnableWindow(Ctl(IDC_CLOSE), !busy);
    EnableWindow(Ctl(IDC_DIAG), !busy);
    EnableWindow(Ctl(IDC_LANG), !busy);
    // Another version installed: "Update"; the same (or unknown) version: "Reinstall".
    bool otherVersion = g_driverOk && running[0] && wcscmp(running, L"" S2M_VER_STR) != 0;
    g_updateAvail = otherVersion;
    SetWindowTextW(Ctl(IDC_INSTALL), !g_driverOk ? TR(L"Установить") : otherVersion ? TR(L"Обновить") : TR(L"Переустановить"));
    InvalidateRect(g_wnd, nullptr, FALSE);
}

static void Start(int action)
{
    if (g_worker) return;
    g_action = action;
    g_wantDesktop = SendMessageW(Ctl(IDC_LINK_DESKTOP), BM_GETCHECK, 0, 0) == BST_CHECKED;
    g_wantStartMenu = SendMessageW(Ctl(IDC_LINK_START), BM_GETCHECK, 0, 0) == BST_CHECKED;
    g_worker = CreateThread(nullptr, 0, Worker, nullptr, 0, nullptr);
    RefreshState();
}

// ---------------------------------------------------------------------------
// Layout

static HWND Create(const wchar_t* cls, const wchar_t* text, DWORD style, int id, DWORD ex = 0)
{
    HWND h = CreateWindowExW(ex, cls, text, WS_CHILD | WS_VISIBLE | style, 0, 0, 10, 10, g_wnd,
                             (HMENU)(INT_PTR)id, g_inst, nullptr);
    return h;
}

static void Place(int id, int x, int y, int w, int h)
{
    SetWindowPos(Ctl(id), nullptr, S(x), S(y), S(w), S(h), SWP_NOZORDER | SWP_NOACTIVATE);
}

static void ApplyDpi()
{
    if (g_font) DeleteObject(g_font);
    if (g_fontTitle) DeleteObject(g_fontTitle);
    if (g_bigIcon) DestroyIcon(g_bigIcon);
    g_font = CreateFontW(-MulDiv(9, (int)g_dpi, 72), 0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET, 0, 0,
                         CLEARTYPE_QUALITY, 0, L"Segoe UI");
    g_fontTitle = CreateFontW(-MulDiv(18, (int)g_dpi, 72), 0, 0, 0, FW_SEMIBOLD, 0, 0, 0, DEFAULT_CHARSET, 0, 0,
                              CLEARTYPE_QUALITY, 0, L"Segoe UI");
    g_bigIcon = (HICON)LoadImageW(g_inst, MAKEINTRESOURCEW(1), IMAGE_ICON, S(64), S(64), 0);
    for (HWND c = GetWindow(g_wnd, GW_CHILD); c; c = GetWindow(c, GW_HWNDNEXT))
    {
        SendMessageW(c, WM_SETFONT, (WPARAM)g_font, TRUE);
    }
    SendMessageW(Ctl(IDC_TITLE), WM_SETFONT, (WPARAM)g_fontTitle, TRUE);

    // 600 px wide (96 DPI). The test mode button is as wide as its longer label (Enable / Disable, so it does not
    // jump), the test mode line gets the rest of the row: "... (until restart)" has to fit.
    int button = 0;
    {
        HDC dc = GetDC(g_wnd);
        HGDIOBJ old = SelectObject(dc, g_font);
        const wchar_t* labels[2] = { TR(L"Включить тестовый режим"), TR(L"Выключить тестовый режим") };
        for (const wchar_t* t : labels)
        {
            SIZE sz = {};
            GetTextExtentPoint32W(dc, t, (int)wcslen(t), &sz);
            int w = MulDiv(sz.cx, 96, (int)g_dpi) + 24;
            if (w > button) button = w;
        }
        SelectObject(dc, old);
        ReleaseDC(g_wnd, dc);
        if (button < 120) button = 120;
        if (button > 300) button = 300;
    }
    Place(IDC_TITLE, 100, 12, 350, 36);
    Place(IDC_LANG, 450, 14, 138, 400);
    Place(IDC_SUBTITLE, 100, 50, 480, 20);
    Place(IDC_VERSION, 100, 71, 480, 19);
    Place(IDC_GROUP, 12, 106, 576, 104);
    Place(IDC_ST_SECURE, 26, 130, 550, 20);         // Secure Boot first: test mode can be turned on only without it
    Place(IDC_ST_TEST, 26, 154, 578 - button - 8 - 26, 20);
    Place(IDC_ENABLE_TEST, 578 - button, 150, button, 26);   // next to the test mode line
    Place(IDC_ST_DRIVER, 26, 178, 550, 20);
    Place(IDC_INSTALL, 322, 222, 144, 30);
    Place(IDC_REMOVE, 472, 222, 116, 30);
    Place(IDC_LOG, 12, 264, 576, 124);
    Place(IDC_LINK_DESKTOP, 14, 394, 270, 22);
    Place(IDC_LINK_START, 300, 394, 280, 22);
    Place(IDC_LAUNCH, 14, 418, 400, 22);
    Place(IDC_DIAG, 12, 448, 116, 30);
    Place(IDC_OPENLOG, 134, 448, 130, 30);
    Place(IDC_CLOSE, 472, 448, 116, 30);
}

static void CreateControls()
{
    Create(L"STATIC", L"Speak2Mic", 0, IDC_TITLE);
    Create(WC_COMBOBOXW, L"", CBS_DROPDOWNLIST | WS_TABSTOP | WS_VSCROLL, IDC_LANG);
    LangFillCombo(Ctl(IDC_LANG));
    Create(L"STATIC", TR(L"Виртуальный аудиокабель: звук динамиков → микрофон"), 0, IDC_SUBTITLE);
    wchar_t ver[200];
    int n = _snwprintf(ver, 200, TR(L"Версия %ls"), L"" S2M_VER_STR);
    if (n > 0 && n < 200) _snwprintf(ver + n, 200 - n, L"   ·   %ls, %ls", L"" S2M_AUTHOR, L"" S2M_EMAIL);
    ver[199] = 0;
    Create(L"STATIC", ver, 0, IDC_VERSION);
    Create(L"BUTTON", TR(L"Состояние системы"), BS_GROUPBOX, IDC_GROUP);
    Create(L"STATIC", L"", SS_ENDELLIPSIS, IDC_ST_SECURE);   // a translation too long: "..." instead of a cut
    Create(L"STATIC", L"", SS_ENDELLIPSIS, IDC_ST_TEST);   // a translation too long: "..." instead of a cut
    Create(L"STATIC", L"", SS_ENDELLIPSIS, IDC_ST_DRIVER);   // a translation too long: "..." instead of a cut
    Create(L"BUTTON", TR(L"Включить тестовый режим"), BS_PUSHBUTTON | WS_TABSTOP, IDC_ENABLE_TEST);
    Create(L"BUTTON", TR(L"Установить"), BS_DEFPUSHBUTTON | WS_TABSTOP, IDC_INSTALL);
    Create(L"BUTTON", TR(L"Удалить"), BS_PUSHBUTTON | WS_TABSTOP, IDC_REMOVE);
    Create(L"EDIT", L"", ES_MULTILINE | ES_READONLY | ES_AUTOVSCROLL | WS_VSCROLL | WS_TABSTOP, IDC_LOG, WS_EX_CLIENTEDGE);
    Create(L"BUTTON", TR(L"Запустить Speak2Mic после установки"), BS_AUTOCHECKBOX | WS_TABSTOP, IDC_LAUNCH);
    Create(L"BUTTON", TR(L"Ярлык на рабочем столе"), BS_AUTOCHECKBOX | WS_TABSTOP, IDC_LINK_DESKTOP);
    Create(L"BUTTON", TR(L"Ярлыки в меню «Пуск»"), BS_AUTOCHECKBOX | WS_TABSTOP, IDC_LINK_START);
    Create(L"BUTTON", TR(L"Диагностика"), BS_PUSHBUTTON | WS_TABSTOP, IDC_DIAG);
    Create(L"BUTTON", TR(L"Открыть журнал"), BS_PUSHBUTTON | WS_TABSTOP, IDC_OPENLOG);
    Create(L"BUTTON", TR(L"Закрыть"), BS_PUSHBUTTON | WS_TABSTOP, IDC_CLOSE);
    SendMessageW(Ctl(IDC_LAUNCH), BM_SETCHECK, BST_CHECKED, 0);
    SendMessageW(Ctl(IDC_LINK_DESKTOP), BM_SETCHECK, BST_CHECKED, 0);
    SendMessageW(Ctl(IDC_LINK_START), BM_SETCHECK, BST_CHECKED, 0);
}

// ---------------------------------------------------------------------------

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg)
    {
    case WM_CREATE:
    {
        g_wnd = hwnd;
        g_dpi = GetDpiForWindow(hwnd);
        g_whiteBrush = CreateSolidBrush(RGB(255, 255, 255));
        CreateControls();
        ApplyDpi();
        RefreshState();
        if (!g_filesOk)
            AppendLog(TR(L"Рядом с установщиком не хватает файлов драйвера (Speak2Mic.inf/.sys/.cat/.cer, Speak2Mic-Publisher.cer). Распакуйте архив целиком."));
        else if (!g_secureOk)
            AppendLog(TR(L"Сначала выключите Secure Boot: при нём Windows не загружает драйверы с тестовой подписью."));
        else if (!g_testOk)
            AppendLog(g_testNext ? TR(L"Тестовый режим подписи включён. Перезагрузите компьютер и снова запустите установку.")
                                 : TR(L"Нажмите «Включить тестовый режим», перезагрузите компьютер и снова запустите установщик."));
        else
            AppendLog(g_driverOk ? TR(L"Speak2Mic уже установлен. Можно переустановить или удалить.")
                                 : TR(L"Всё готово к установке. Нажмите «Установить»."));
        return 0;
    }

    case WM_DPICHANGED:
    {
        g_dpi = HIWORD(wp);
        RECT* r = (RECT*)lp;
        SetWindowPos(hwnd, nullptr, r->left, r->top, r->right - r->left, r->bottom - r->top, SWP_NOZORDER | SWP_NOACTIVATE);
        ApplyDpi();
        InvalidateRect(hwnd, nullptr, TRUE);
        return 0;
    }

    case WM_PAINT:
    {
        PAINTSTRUCT ps;
        HDC dc = BeginPaint(hwnd, &ps);
        RECT rc;
        GetClientRect(hwnd, &rc);
        RECT head = { 0, 0, rc.right, S(94) };
        FillRect(dc, &head, g_whiteBrush);
        RECT line = { 0, S(94), rc.right, S(95) };
        FillRect(dc, &line, GetSysColorBrush(COLOR_3DSHADOW));
        if (g_bigIcon) DrawIconEx(dc, S(20), S(15), g_bigIcon, S(64), S(64), 0, nullptr, DI_NORMAL);
        EndPaint(hwnd, &ps);
        return 0;
    }

    case WM_CTLCOLORSTATIC:
    {
        HDC dc = (HDC)wp;
        int id = GetDlgCtrlID((HWND)lp);
        if (id == IDC_TITLE || id == IDC_SUBTITLE || id == IDC_VERSION)
        {
            SetBkColor(dc, RGB(255, 255, 255));
            SetTextColor(dc, id == IDC_TITLE ? RGB(40, 40, 60) : id == IDC_VERSION ? RGB(130, 130, 140) : RGB(90, 90, 100));
            return (LRESULT)g_whiteBrush;
        }
        if (id == IDC_ST_TEST || id == IDC_ST_SECURE || id == IDC_ST_DRIVER)
        {
            bool ok = id == IDC_ST_TEST ? g_testOk : id == IDC_ST_SECURE ? g_secureOk : g_driverOk;
            // Driver of another version than this installer's: amber ("Update" is possible); dark enough to read on grey.
            COLORREF color = id == IDC_ST_DRIVER && g_updateAvail ? RGB(200, 140, 0)
                           : ok ? RGB(0, 128, 60) : (id == IDC_ST_DRIVER ? RGB(90, 90, 100) : RGB(190, 30, 30));
            SetTextColor(dc, color);
            SetBkColor(dc, GetSysColor(COLOR_BTNFACE));
            return (LRESULT)GetSysColorBrush(COLOR_BTNFACE);
        }
        break;
    }

    case WM_APP_LOG:
    {
        wchar_t* line = (wchar_t*)lp;
        AppendLog(line);
        free(line);
        return 0;
    }

    case WM_APP_DONE:
    {
        WaitForSingleObject(g_worker, INFINITE);
        CloseHandle(g_worker);
        g_worker = nullptr;
        int action = g_action;
        RefreshState();

        if (action == ACT_INSTALL && g_ok)
        {
            if (g_reboot)
            {
                AppendLog(TR(L"Перезагрузите компьютер, чтобы закончить установку."));
            }
            else if (g_diag != DiagOk)
            {
                AppendLog(TR(L"Драйвер установлен, но звуковые устройства Speak2Mic не работают — причина выше."));
                wchar_t t[400];
                _snwprintf(t, 400, TR(L"Подробный журнал: %ls (кнопка «Открыть журнал»). Пришлите его разработчику."), AppLogPath());
                t[399] = 0;
                AppendLog(t);
            }
            else
            {
                AppendLog(TR(L"Готово: «Speak2Mic Speaker» и «Speak2Mic Microphone» появились в настройках звука."));
                if (SendMessageW(Ctl(IDC_LAUNCH), BM_GETCHECK, 0, 0) == BST_CHECKED)
                {
                    wchar_t panel[MAX_PATH];
                    if (SetupProgramDir(panel) && wcslen(panel) < MAX_PATH - 16)
                        wcscat(panel, L"\\Speak2Mic.exe");
                    if (GetFileAttributesW(panel) == INVALID_FILE_ATTRIBUTES)
                        SiblingPath(L"Speak2Mic.exe", panel);
                    ShellExecuteW(hwnd, L"open", panel, nullptr, nullptr, SW_SHOWNORMAL);
                }
            }
        }
        else if (action == ACT_TESTSIGN && g_ok)
        {
            if (MessageBoxW(hwnd, g_testTarget ? TR(L"Тестовый режим включится после перезагрузки.\n\nПерезагрузить компьютер сейчас?")
                                               : TR(L"Тестовый режим выключится после перезагрузки.\n\nПерезагрузить компьютер сейчас?"),
                            L"Speak2Mic", MB_YESNO | MB_ICONQUESTION) == IDYES)
            {
                wchar_t sys[MAX_PATH], cmd[MAX_PATH + 32];
                GetSystemDirectoryW(sys, MAX_PATH);
                _snwprintf(cmd, MAX_PATH + 32, L"\"%ls\\shutdown.exe\" /r /t 0", sys);
                cmd[MAX_PATH + 31] = 0;
                STARTUPINFOW si = { sizeof(si) };
                PROCESS_INFORMATION pi = {};
                if (CreateProcessW(nullptr, cmd, nullptr, nullptr, FALSE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi))
                {
                    CloseHandle(pi.hThread);
                    CloseHandle(pi.hProcess);
                }
            }
        }
        else if (!g_ok)
        {
            AppendLog(TR(L"Операция не выполнена — подробности выше."));
        }
        return 0;
    }

    case WM_COMMAND:
        if (LOWORD(wp) == IDC_LANG && HIWORD(wp) == CBN_SELCHANGE)
        {
            if (!g_worker && LangApplyCombo(Ctl(IDC_LANG))) DestroyWindow(hwnd);   // a new copy starts
            return 0;
        }
        if (HIWORD(wp) == BN_CLICKED)
        {
            switch (LOWORD(wp))
            {
            case IDC_INSTALL: Start(ACT_INSTALL); break;
            case IDC_REMOVE:
                if (MessageBoxW(hwnd, TR(L"Удалить драйвер Speak2Mic и его устройства?"), L"Speak2Mic",
                                MB_YESNO | MB_ICONQUESTION) == IDYES)
                    Start(ACT_REMOVE);
                break;
            case IDC_ENABLE_TEST:
                // Switching off with the driver installed: it stops loading until the mode is on again.
                if (g_testNext && g_driverOk &&
                    MessageBoxW(hwnd, TR(L"Без тестового режима драйвер Speak2Mic не будет загружаться: звуковые устройства Speak2Mic исчезнут, пока режим не включат снова.\n\nВыключить тестовый режим?"),
                                L"Speak2Mic", MB_YESNO | MB_ICONWARNING | MB_DEFBUTTON2) != IDYES)
                    break;
                g_testTarget = !g_testNext;
                Start(ACT_TESTSIGN);
                break;
            case IDC_DIAG: Start(ACT_DIAG); break;
            case IDC_OPENLOG: ShellExecuteW(hwnd, L"open", L"notepad.exe", AppLogPath(), nullptr, SW_SHOWNORMAL); break;
            case IDC_CLOSE: PostMessageW(hwnd, WM_CLOSE, 0, 0); break;
            }
        }
        return 0;

    case WM_CLOSE:
        if (g_worker) return 0;         // do not close in the middle of an operation
        DestroyWindow(hwnd);
        return 0;

    case WM_DESTROY:
        if (g_selfDelete) SetupScheduleSelfDelete();
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

int WINAPI wWinMain(HINSTANCE inst, HINSTANCE, PWSTR, int show)
{
    g_inst = inst;
    AppLogOpen(L"setup");
    AppLog(L"Speak2Mic-Setup " S2M_VER_STR);
    INITCOMMONCONTROLSEX icc = { sizeof(icc), ICC_STANDARD_CLASSES };
    InitCommonControlsEx(&icc);

    WNDCLASSEXW wc = { sizeof(wc) };
    wc.lpfnWndProc = WndProc;
    wc.hInstance = inst;
    wc.hCursor = LoadCursorW(nullptr, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    wc.hIcon = (HICON)LoadImageW(inst, MAKEINTRESOURCEW(1), IMAGE_ICON, GetSystemMetrics(SM_CXICON),
                                 GetSystemMetrics(SM_CYICON), 0);
    wc.hIconSm = (HICON)LoadImageW(inst, MAKEINTRESOURCEW(1), IMAGE_ICON, GetSystemMetrics(SM_CXSMICON),
                                   GetSystemMetrics(SM_CYSMICON), 0);
    wc.lpszClassName = L"S2mSetup";
    RegisterClassExW(&wc);

    UINT dpi = GetDpiForSystem();
    RECT r = { 0, 0, MulDiv(600, (int)dpi, 96), MulDiv(490, (int)dpi, 96) };
    DWORD style = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX;
    AdjustWindowRectExForDpi(&r, style, FALSE, WS_EX_CONTROLPARENT, dpi);
    wchar_t title[128];
    _snwprintf(title, 128, TR(L"Установка Speak2Mic %ls"), L"" S2M_VER_STR);
    title[127] = 0;
    HWND hwnd = CreateWindowExW(WS_EX_CONTROLPARENT, L"S2mSetup", title, style,
                                CW_USEDEFAULT, CW_USEDEFAULT, r.right - r.left, r.bottom - r.top,
                                nullptr, nullptr, inst, nullptr);
    if (!hwnd) return 1;
    ShowWindow(hwnd, show);

    MSG m;
    while (GetMessageW(&m, nullptr, 0, 0) > 0)
    {
        if (!IsDialogMessageW(hwnd, &m))
        {
            TranslateMessage(&m);
            DispatchMessageW(&m);
        }
    }
    return 0;
}
