#!/usr/bin/env python3
"""Builds app/lang_table.inc from app/lang/*.txt.

keys.txt   - the Russian source strings, one per line, exactly as the C string literal in the code
             (escapes like \\n and \\\\ kept). The first UI_COUNT lines are the user interface; the rest
             are technical diagnostics that exist only in Russian and English.
<code>.txt - translations, line N translates line N of keys.txt. Missing lines (a shorter file) or a
             line "-" fall back to English, then to Russian.
Every translation must keep the printf conversions (%ls, %lu, %08lX, ...) of its key in the same order.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
UI_COUNT = 251

# code, native name, Windows primary language id (winnt.h LANG_*); the order is the table column order.
LANGS = [
    ('ru', 'Русский', 0x19), ('en', 'English', 0x09), ('uk', 'Українська', 0x22), ('be', 'Беларуская', 0x23), ('de', 'Deutsch', 0x07),
    ('fr', 'Français', 0x0C), ('es', 'Español', 0x0A), ('it', 'Italiano', 0x10), ('pt', 'Português (Brasil)', 0x16),
    ('pl', 'Polski', 0x15), ('nl', 'Nederlands', 0x13), ('tr', 'Türkçe', 0x1F), ('id', 'Bahasa Indonesia', 0x21),
    ('vi', 'Tiếng Việt', 0x2A), ('zh', '中文(简体)', 0x04), ('ja', '日本語', 0x11), ('ko', '한국어', 0x12),
]
SPEC = re.compile(r'%[-+ #0]*\d*(?:\.\d+)?(?:ll|l|h|w)?[a-zA-Z%]')


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read().rstrip('\n').split('\n') if os.path.getsize(path) else []


def c_lit(s):
    # the files hold C literal contents; escape bare double quotes only
    return re.sub(r'(?<!\\)"', r'\\"', s)


def main():
    keys = read(os.path.join(HERE, 'keys.txt'))
    columns, errors = [], []
    for code, _, _ in LANGS[1:]:
        path = os.path.join(HERE, code + '.txt')
        lines = read(path) if os.path.exists(path) else []
        if len(lines) > len(keys):
            errors.append(f'{code}.txt: {len(lines)} lines, keys.txt has {len(keys)}')
        col = []
        for i, key in enumerate(keys):
            t = lines[i] if i < len(lines) else '-'
            if t == '-' or t == '':
                col.append(None)
                continue
            if SPEC.findall(key) != SPEC.findall(t):
                errors.append(f'{code}.txt:{i + 1}: conversions {SPEC.findall(t)} != {SPEC.findall(key)}  [{key}]')
            col.append(t)
        if code != 'en' and len(lines) < UI_COUNT:
            errors.append(f'{code}.txt: only {len(lines)} of {UI_COUNT} interface strings')
        columns.append(col)
    if errors:
        print('\n'.join(errors))
        sys.exit(1)

    out = ['// Generated by lang/gen_lang.py - do not edit.',
           f'#define S2M_LANG_COUNT {len(LANGS)}',
           'static const S2mLangInfo kLangs[S2M_LANG_COUNT] = {']
    out += [f'    {{ L"{c}", L"{n}", 0x{p:02X} }},' for c, n, p in LANGS]
    out += ['};', '', '// { Russian source, translations in kLangs order from index 1 (nullptr = fall back) }',
            'static const wchar_t* const kText[][S2M_LANG_COUNT] = {']
    for i, key in enumerate(keys):
        cells = [f'L"{c_lit(key)}"'] + [f'L"{c_lit(col[i])}"' if col[i] else 'nullptr' for col in columns]
        out.append('    { ' + ', '.join(cells) + ' },')
    out.append('};')
    with open(os.path.join(HERE, '..', 'lang_table.inc'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out) + '\n')
    done = {code: sum(1 for t in col if t) for (code, _, _), col in zip(LANGS[1:], columns)}
    print('lang_table.inc:', len(keys), 'strings;', ', '.join(f'{c} {n}' for c, n in done.items()))


if __name__ == '__main__':
    main()
