// Generated by gen.py - do not edit.
#pragma once

#define S2M_MAX_CABLES 1

// Pin name GUIDs: [cable][0] = "Speak2Mic Speaker" (render), [cable][1] = "Speak2Mic Microphone" (capture)
static const GUID g_S2mPinNames[S2M_MAX_CABLES][2] = {
    { { 0x6001C8A7, 0xE8F5, 0x4058, { 0xA9, 0xE5, 0xFC, 0xD4, 0x88, 0x3F, 0xF6, 0x8F } },
      { 0x28846C9C, 0x5B44, 0x464E, { 0x85, 0x59, 0xDB, 0x62, 0x48, 0x54, 0x19, 0x63 } } },
};

// Subdevice (KS filter) names = reference strings of the device interfaces in the INF.
// PortCls keeps the pointer passed to PcRegisterSubdevice, so these must be static strings.
// Order per cable: WaveRender, TopoRender, WaveCapture, TopoCapture (see S2M_SUBDEVICE).
static const PCWSTR g_S2mSubdeviceNames[S2M_MAX_CABLES][4] = {
    { L"WaveRender0", L"TopoRender0", L"WaveCapture0", L"TopoCapture0" },
};
