// Generated by gen.py at build time - do not edit.
#pragma once
#define S2M_VER_MAJOR 1
#define S2M_VER_MINOR 0
#define S2M_VER_BUILD 278
#define S2M_VER_REV   1328
#define S2M_VER_STR   "1.0.278.1328"
